apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t9GlFBmvjIDEu3AzNfPz2dtMto4Rky+OMukXwHe+QxboMpq15ks33WP0A0Uwe7hknIhgAS+F11EEXWwHNG/cr7vqsBLzcLUpnQV4nQXZqq99nvSjrBK42MJKQjA4PtYsCuDyvIP9Mkahd8b793M9vFJ69GaQ00ROujEviPY9AzXZIQ5cdW8bGenTMywRJ+m0Qriehcz9nhUbhQnJdBhLlkW1uhc8IIXKkT1SotwzenP2i93gY4l6zXhrRL+DJFhBl059RK/FlyMA39yYF2kuBYvA8BipXrUZBLqzLqdSN/wIBMcBvYZVRS4fdkrMURviOMx1qkCxuzcHgDgPS50zXb9rF923ePJ2i+V6KQD3M9msELwvk11+ckYoe7qMnttB,iv:IxcEmNQQWBMxaUhDfvMFrlMNZfIeVyeXTSDYydj7qKI=,tag:KmD2W63iw8rzMru5qHgu4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:6P4HmPKKsMLYI03sQjK9OSnv/SGwGuk/suIf9rDy+sgcNzDAhUsY+S/Kjg/xkbbTlVc/Ktf6ORM89jCzerGKFeE1uZtAeyo6qRo6hz5/jkmf8g8ubSa/fgIkmHnelSXu3g712eAs4GEzw71R2jNZDuECJJZX4WPtZoQmanAvUs4Q9NV8q2YU87nO0pVhvcofnJG/vdm2+Yfog6NWnJ4xqUD0Pm+jhwqMZDUuoZ7KARsBk6P912I/gyQROeSfko62JXHuOJbobfv8aRQH6A==,iv:MO9HQh20VSyKPfeZygOZ05Hgx5qhfyKsK6Wy5h8pzdM=,tag:6arArMoIlHgnSVTQ4dFSKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:OmD/6KMxjXaHFZ34FTRhu8Op1s8P/nrNkX9R2jm74K72mjoX0dRvzrIrLB+7UK20ihmKTiCwLFNlMnLXNDQx+nJe3LZRWOotG9I3g0C6lnObg991B2Hsm54xEKpX19sHm/jYecJiw7gJ6ZcNDESjwn+JSlvt1R2J6942RrtnNPw61AHeFL3V7aYyTubtgCfkPSRqcS8woIuH8CqehWRdpyzqM72QazIEzM3Q,iv:NDf4uS1V8mYfDK9gnhWCHW/INffgokqfRvlqTiANPos=,tag:5m9wP89A10UqLqoIN2zq/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUlJjMDM1VnZpM0Z3Tlgx
            cUltbTNxK2ZLZmhkVWJQdkFHd3YrcFBxVnhjCjJUZzcrS3U0RVVWK1NLL2pWdEdK
            VDBJcUFPVXZhUWR2enJFeGhDaTQzNDAKLS0tIDYwdGtBUWVVSE5oaDBNb1c5MWRr
            UVlQWi91UEVOWlVZUUxzT3ZYY2NDYzgKefXgkHYWJOII+KccnWej4MIlno2Kn8Ll
            N2oq1e8xyyLJWGmFqDfV7/08wVrNNl9zOIzv1Emcw/NYrzqufwMJIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T19:37:15Z"
    mac: ENC[AES256_GCM,data:sWZJV4m0gvPD672K8ky1Dg1WjGhhvBKUl7RNl+kj9XxKE9EoMm0XS4ajPIKHxU3zj1GiY1TTSuwtSlQxmt6wJ2AeXD5eX7Wawv1cV0IH9W+USEny5JRHAql/xJHTQHnAJ3A9K6Xv9YWheHIMw6jN7ubySknPK+PNMg6+i3uTUgg=,iv:eiX92tGI2DCrErtv4ITTDM0B/4ounPyxS7VlyGjgzXA=,tag:AQ8XG7fYNZA5HB/s7G/69w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
