apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1/T03apA8Tvw9yXccuLlMMX21gdKNc20UvhyDsgrddTJlSPmyY1xmYIgKDBrfrHP3Iu84fihl+vHiFIFcGw81Hacex9KpB14m35OMN8lWWgALpjSv0y6GrXkPZEAuUfSzeVSGEfvGwMneoDjIq+bHi+K4TlLdGDlyUk3zTaTkiinU/NLDbb4fZlaiw9OwRamuHgumKb77RFIKgHIOmT46DTnnQL4nGa4eqQZNrrkmq8Lq8Vw59fO9tSwxzHLccvJGgVy6pSFHvr+DVkfZAGe5V4wY9UHjTjYGDioKtcWwF4xDUO5kvDLdvxcYCdUPvmIzaDcVCMzlkKuUJEMOLodqc6aV2TgKSWtFd9yKW9GIKY6hdrktRxCFMIrhYhVj9zg,iv:QH5E+4m8x8zNiM9qL1kCU+sxfuQvmuZnh7S5D0+b0Eo=,tag:a1z7MrpcFMNHSNjU00lcVg==,type:str]
    identity.pub: ENC[AES256_GCM,data:urJr0+12zfpxwrK5es9el2CiXU+LxlwVbnE4Go9LaHOJ4hrMlLhywsNsjWeKn47X2nznGuvDWBt/ozbuHHEb7lV9aA3hRyZnJR6KYJ2QroOApf7JSRjZPyvEmlH7PqU0NUk+HScC0yAUZHIWt5nZYgJAHXcBNv4uN7CWmVOEaKC7rGs3j2UIo2zYMNRS/eoqnerbHvF1qzN4TqGfTSIP1wOxIpbB+xzKBufVlsjIq7N99Omoi2/fH3OFUCc0dUfq6hKnAShamXj1AsEBfw==,iv:c/X3Yjo0bPKXWIWPx1QwXj758qMO9qXTFJ8XQGC4LVc=,tag:vpA6b1Svz2B5aZOik8nCBQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:0RtgWDOpGzy95kgeDYa9FRUKH/rfxlbQPePe3/vlCqLauWA6FAEdi4gCBZrkOlj1EI/drqzDaK9R2gVmPmFfeTCAwTxEjO7VFHIcv7+JAvwwHUkJOdLYzl/h+1IK9Vwc2j7pJfriu1sZAfM22zrhZpjs5TIKD69X6ds8TRLIoXRvtPt5T2UAdGNdtvUthKUGnUc7H4QwSxgQBRZTEzoDxlNATdUTS0zZ6hwo,iv:ktZC5i653jDLnxUOiggFdiuJuZvS4Cz+KCjTgKf+kt0=,tag:bfHtRntDQw0+YPm57hoSNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYU4rYTFJREY4NVdFUGJH
            WmFWMlBUWFRzaThXc3BkWDhuOVRrb01SNlFNClVrQkx6TnBlNTAxamxwSVFEQ1ZT
            b0NlYllRZHV2LzRXeGhLVERSTXA3blUKLS0tIDZSVlh3Qm4rVUp5b3RHMmMxUGxZ
            K2kzMElvOWdoTUQ4YlozRlVINmFpSGsKTg6aoXlmDHFSUkflgbVNqF2gp2iIxSuf
            wrs7sHwCVyf9Kl0sQaKaLaXhHaFE3ewDPOrAxvhactBTceRlUqOcVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:40:42Z"
    mac: ENC[AES256_GCM,data:KcwCpKZo3MdPC0McCu9vRo7lIBqemwvTYCzd9yJbp452t2y7jDdxMhLYFCIXBYIps+TwwoECUocnbovRLPxsR+HykdiT12E9THOCzmBPhfcF5N4gY5n1MaG1A9vvgTBmU/oaewwPOiFEiVKezewJIo0eC5APAbti/lm6dKbaAyI=,iv:nqxTBvwJ4tyA06mtZzp2PJs2WRlH96OY00pyot8jiUY=,tag:Tk6G9apWLiGrmH+AGJ50OA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
