apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hKjK/zg8g2rXbX9wBK/bAId8nhtyULQkwvJY+T03qCmGjKWBs8lqrIRdWsjYWMASQhtCTAYge/kiuyWCcD3chnd4BNaZD0qypHrRT7TKaW+LNpyKB/VOQNC5Dv/P//lkYJarpfFapDJACvOdBY+9CDBwyRpRTDWS2x4yaeRmKvWQh/wC1jfAaJAEm/b8Sh556ZX8sMzsK+M7rvxRamouurrhcsT5U24/m2Bim3qGpW7oBSXqYY5v1+hbSZrAtUkktxEW9vwmaHRGNyjbx9PeOvBjajHPkaRNSSSYT0yZbK94PIHxzBf67lhY3VgCfNMzAgPMUDyHfAlS+UNU42Za8am/W3EFu7fXBRBC03nuNLmV5Xjm74ZYf9YObIkiz/7R,iv:QiCcvh402e/xKhUZNZOPlFEUfl5IVbFXCMuXyw2Ehf8=,tag:at+SVE2LyoXY6gQ/pDikcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dBBqIyZskpsVWH16aC8g8RkJwE0RynI7JzYz8pi+kKwUiEvzmZ6zJiuUt/jQMB8xKMy9YGEbTqc3PauGT/NFiVDyN6rXr5LoQC+NzDmN6agU+1uxkj07IgCe9CiZh2cC7S9luEEjzVQ5oomhu4mhJAjrq6zO4K2O6Omk8e3wpkEPk3075/rAA3M8P+1iie94Eur7kXsg2ZwJ+zl+WV9B8N6GwERut+GNVGn+TdXARRfC2OVyzo+BsKiuFoKGNKQJHRWPYm2FI6lkmINQoQ==,iv:F4bvu3FMVDIwE5y/DPvZfsR7WOrMPZRHoPVHYwEya7k=,tag:2ELfShmW/bkZocd50G0f2w==,type:str]
    known_hosts: ENC[AES256_GCM,data:6tnDo3FWQzgB08Y+EAazwK+eLEfmSoaHobRfEplQPY2DX1c5aMhl1gnoQVc/prG/og34ALycxI6Rms/LpflB0Lp8CBimfKTU6roHXyc7y1O+mn8rSajn+FmZ4xpYZlL5uGIGGAHiwCW0cMVdk1/6WlZhnKvldgDTYHa/Ls/1xp58rwY9c7/6NEHgIaVOq0Bmpj+5IuqXGBFhbG4ysXNcSiggT1+kMDMEMrMJ,iv:VtNkqtJAjEuWwmC5fgQBT96EYNN3kzVGT+hVIxupZVc=,tag:FYdiUhXvOGpiWE4jf/cUlA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYmFtSmVCay9iY1JjQmJx
            bjhOeUJ4NzlPN0dDVktTamZyVVhsRnlicVdBCjVGQzYzV2JIRTE1WTBEbkF6NlE2
            OEFPQmpjOFJxL3ludWozMEZnRW1sYmcKLS0tIGZ0U2FwRk1iRy82bjJZTWptUUVE
            RkZZbVlEVTRiaEVlS2hBOXhjZ2Yyc00KaYLs/Orf3ky60kbiB/K1Z3Qc4T/dK4V+
            IvFXK7N5XfQb88LJpTW9ADExyy/avRZCSqKsrRfsGlwKfKuuwQ3fpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T17:29:45Z"
    mac: ENC[AES256_GCM,data:x18mcsoKD27CV+4HkZ7d1dx6T1NJrRW/qFkDYIKn3At4uBR3d5dUnHGLeJPuEj6fJvs2cEChbLgYHwRswcc+DTwnUYufvoLp5rmuGZ+V1NLQ5Oe56PxHx0Tw0bxH9PFHVRrZ4eTP907KjTwu+jgHoBL/DxH62HEzj1K5196RxK8=,iv:QqVIuVvKe9aX+sABdMpHxeMd8l1yyugJvUnhSnKVZkw=,tag:3Dkj3z46Ye5u+JtGCpMcpg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
