apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zgJPxuSfsOTSCEMyAgVJdPTbniUJh+0pfrmZThyoO6f7tiGYOHO5D/Apm8ZS8v8IFvITS68JlkItlev8yGRQth8OUrXGAQt50M7tjeb2omAxmUzK578mCp6GSUzxOnwvyYVo/7qHN+OATuZhdt6LxPFTigUCcVLobNy9XvWMHWcZ4x8HWOcItA7KcWMBCsnNWUR0bpfoKyPxiqWdRWi98qKaTgj4ptlgf3Gt3uY3tTOjlwx8KwUZ3mUI1hmqAqgQufp4zbpwlXSk4o6cTWGUUC++OcE16EIuY6Ha9mMNMH3JLTWhxGp8Plh6I/K0Kv9Qty4goGDJyOesT3j2plDvFfl5clsyR9E31TaOP56746SEcvS5yY7V3YOh7I30sK8i,iv:sfH9KXtbkEBaClBF4HR1zRz8ac5oY7l+rlJLrpbr/no=,tag:6A3ZWHxI5kdotm+wk6KqLQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:YwRmWA/CZJt/YGcUH/VjrzQNZjUQ33/4B6L3sVpgUF3ZFJhF/9yNzBwl/CM9T3fF4mmbBGB7XFuM5/f5GtbOLlWks6jP/z5S/x415g4RRuXLzY5QrxOrQsEUcuP8xVbe+BrMHgYIEVYf8uogQXPgp2cd7bMFTlyTfLkkuDUyqXTg2L0wkpyAtyFQLRMl6yH8bleYad9V+vVbKICBci83jt3L/n6MnVUjFkMO2JnPKYshkg82y4b1t0iM0hXcGyWPvwBNEP9rN2NtRDtkUw==,iv:5YW5doTPBfyewsBdwhDHjI8WRM4E5TlAGcr1aRvUQL8=,tag:iTENsgFvOFiqO7Sln9ytOQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:WpqGQGMYNnrBnqeeNGieXn5fTrhjDEoMScAlXUOyLftc31HrXYnrs24ngqGZRTwhbGmwfOE82eGX8aZiH77D/KFbOJWIEkV5lPGkdGLn72bbTA38gKPsDJid+W6TYt4Hpvakyp7YvQQqeSr2SFRqDfndrv9mmCP3YaxcxyYkpK4J3p2z7f52EiwPXtGlD/r6a35uq8jFHanU9BedXRyKmvYuEN2X2K726+pI,iv:eyxqkhwi1kRH0G+E1PJCUnKk4nj8Lfk3zfWiNsrin+A=,tag:SCriY+sVFjel7rkrVl6nvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZEZNSzlTekgvalB3OFNY
            SXloeWs3dThSbTBsa1RPQWF6YmlvemczQVVRCm5kdWVHVGdXWjk3WVVpVmFMK0lH
            WDJUQlNWN3dOSzMrSjlncks0OXAvZVEKLS0tIENSYS94K01BTG9ZNmV6OXFaaDZI
            czhiOVY3aVVnWmVBbzRNWnZ4dC82Q1UKrT/ggT9J9sPREW4yA1oM0f/oMnUIG9TY
            M11AN5zPltXU6OHPS19oRnz6OK11SaqzKNWpWPmq+gfM6jjMYaud6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T22:32:10Z"
    mac: ENC[AES256_GCM,data:gKHLVX9SdIlRxpBO1evu3wd2wUYfv4HuXA+PHkv3bjeuipRBEdXKseh4GR7RC+3nR1UEuHzaAGSSXzbHtB7IxkZ5n7ckitn+FfJXc1fagiWFKqtTEj66pEuhQqFuTAK2YLt8xWl8zLb8hq57SR4h1nwzfPQgNQn+La5n2yPlwtQ=,iv:iS5aBjPZPi/xDORQlXm8XlceJef3337bBwPa0nWzQ9E=,tag:q1ZB3a9cF0Q4P/eHmykjtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
