apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:b6RyfBKluc+owaqPKA3DzJLh4cprzsyksh7E5QIFBZkfTlPFCq9o0t/QOmWKeHyLeC+xH+IMLzZUKKa30FW4nBV8ZD5FFsIzV45hBy30+6Ftj1Ep7gpkEyB2oMVLux8YOwkyAXCXuFHKyUg9qnrgYXeHanYOfvQHcECYP6xdzdH/yX+GoQXDyDyvfCVGiXsmDPF5fcEsGWTh0IFojiCBAhVQH1zhjX1kXcQ3769mU/AF2KKibA0K9xEM3eVwdCebf8pgsauL3VNse82cVf42j7T2cr2S8LaXfgf2+7/NAEVhuWiJuC/ZMRk8FDSSvLpvwXSKaBX00mX5+h39VijLy/7ORXdpt3R+tRiKucyA4Vx3Nzmzotyd8LZOmRf78q62,iv:daOTxZ5+sMQoh86MsU6+E223Gby1w0Vp/UXS7Nw6NMc=,tag:YJ8TlFwDLsJ+ypLvMTcX7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:GU+DzixqXdhm6W44YrpCz98FiMz5GOkoAmaYv4yOg9flPBZ9o19RT9oHDpRAdKHSsVTlxZENV4m1HUXe4vILhqoSdIc8FjjkLKTlcW2aFRGA1M3rpy+frhx+J76mB+8W1bSkY+zDSgUr4J6zdpuE2trFn9HKliH389Yx42pixuSUvH6N394AHTpZ8LIjluIuB1P0ZFbOPF1n4Itg2h/IJvDT3YeqDPxNxxUzLabvGy/PTJ1bn2OOqjaTjiO4NTx5nbL7srWMq+mpaYkCnw==,iv:czzVo2o1E1r4PbqmJz1y7do+bGXsHvhAr7VzWa21EeQ=,tag:LvszelSChloz9qJ5rXbEYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:m8gzaWBD7RgiAJgWLQzyjbKK+SFu6D4ecLvCXuo5c0m6lI80v2J7rif6FmboKRHppIQrHpgS5SYr1Nz8Oj6G2bePb5u/qMZlwd6gVHQGnJza6EsT55/bYnNcYuDr7dLEQ0zm5FFEM1bl1xDkmzogEKvyh4B4aPvF95gHOOQE/1yz0lrCEDA24EqIsncssA/RClgJ8XU41nrBDmmfatFED5seVtUHEFUKiT3o,iv:+6ziZknyjguPXY56cPzhUJgyOUTOuPW+hfkwNjz7JXk=,tag:bpcZhp4IWx+aloSQJeI9iA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UUxReURpL0ZBdDNFVExS
            Mk5RL0h4RGdZZlJFT1kxRVdEM0xTbm9QWUJRCnJDMkc0YzRPYlJHNUZiY3NmR0pm
            WnBDRWUzcHg0WHB6bEhVYWV3T2h1ZU0KLS0tIGh6QUI0RlJobzgyNE9KdmIrbEp6
            QU1WYVBNM25KSGNpWEVOQXZ2SHdWSFEK/Ypvg/CphaF8ltdrCjZeQjps/skMho12
            bYLJLO2PEJb3vBUauayAfIP5D1udqCUGs+wIUUH4d8naPynHt/Oy+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:13:03Z"
    mac: ENC[AES256_GCM,data:0GUvNIezss+ZRJh9rm2TczDerzU1rlSsPHN6DsjvJa5H8hCVjh0XXOQobSWxd6r2hO9/ePrGfFD5rHSvHhOXp1bOJr+aORjyPo5KErv+T4cdL6Zi8Dr9FrSIDC/tGMtqvuv5V2AzlryRol8RluGMBlT7JJKKdptMh+AHvfNmVrA=,iv:Y3190r0xWjZ163leLHMPn3XxI8N/Ae3y26Q4h6u+HLw=,tag:xCe3Ix5O3vHpjD/6agYH6A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
