apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rZOvv3E2jUkKieF60HIC8sG9p7cAxqQchUVKalegibVzU9BOI0M4Vd5jFdIzH/BGrvqEy1Ir+QGy2KjXm+aav/vMSDAVH/xk8q4EECx5QYrDr8DwZgYC2SPJsdWbL1NOQbPq7qLejubWcTqfozU605gEQcMpUhYTL0WhTyh3K1gxAhtubEpJW/BjC1uDN0b084KR4/HWD6/Bk0eZW/YpidwM8vw+/fvPkPPu4/Tr/vedvjlI2VPBodEX2n72ZedKZygE9+9NBMpWKcrI03xcg2gKVP/H0rizj/mh4yVhpgjiFUAnjWgfOeS3YplWYzWtmjrG6dRb+ea90qewfWjCDUJNvhxQ2a33lX4rXcoNnXkjnsf5IHz40b3SDTN1IyUT,iv:0kjpY3h4KClraYkp5RM5672aDOavF5MbfG7Hy0p9kII=,tag:bg6uBcn67koOJX7wZ5sQmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:hvbGaZhan+VMmez6IiDiJAG6icBYBgr3DvhOYH5dU0iBqTTMrqoIWA9o9h9djZnG6U8xNneIFoIgHLJkzBBEr2Igaj3veHlvt7spz29ZuW1c/5F4MrFHVu/oWbzlkb4n1ssuUJn9cu9sP8FJGW/r5t77kjttHJP72xNyaOGDojWSPXnK4AhCl3m2Zvt1SinJI7/Q+kthR8vCHcN7V2ht+TgD37HB8X/IK7Zj4NmLvxZKxqrQeXSP3DFo+IDdO4p0DJYWyKBO3AdCLLq+pA==,iv:qp8NgydZocM/bu32kaMt+FROol3xj3/gOhvrYQX08c0=,tag:WE9qbKrQ34PCJpa5Sl08Pg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ffIQb5ZPIynOjXEHc7NtSQL5x7pTN02YFH10nEZZqQt9I/6kiL7pbJLCasRDTWPgUDWHcE3y8f4i3+ukxyllw+Rt4vGgvJ1vbbNSvdnU1TzybWA8GOGt3RFvK5MM6soE4qLXeZs2tO0s+pTm1CZypyUN42nvwKhqYrCWAnfw0L5w5uI+XH1gixgcppMU09yzZHB/Q08nmrD+aTZk6daaVfYEfzQ7xeY4SBU5,iv:+4iw5q62vH+1s8pQKDQX6pz6Fel4GWoUpBb87VRhJ3o=,tag:FX+McxGpDTiRqWzu5aqC7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdXgxdlYvQXQ4WnFOcFNy
            YmswdWF1REloMU9XWktHUVB1MlduNlVrWmswCk4xaDV4NWxrOUZvb0N4b3NhMVZR
            MHZ4dVl6M2MweHAyRHg3VGtUMDdnWncKLS0tIG1CRE53Yjd1b1VzeVJ1ak1razU4
            bEl5V003OTdJaEtTb0VUUDlaRjFya0UK5QJv3MbcBYZyzAB2ocVafCHvcHoUxQlR
            0QWwMP+uSMlunUUow01En1jwNbpjYnWsun5K2CDLvd2NTAa3GqyLdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T00:40:15Z"
    mac: ENC[AES256_GCM,data:jttSGUHhQVZHwas7/zQl3/PW5WnKiwlpLp2dfZG1rdZNuHj8tinSA6vt4meYat1CeEAkTE7tFc/aBMnsCVKT7jS3Pt47Z4YmdgPfdhVYcf2quRQxr/ELTjfvHtccNAGpKBCvlAHh3e7lyuD8dRofDK2+w2YKdo/JH6kVM6k1MFY=,iv:uC8ifn7IOAmOrAgZNE9DXh6aHvi8ARjLf3yyZTy7vcA=,tag:xfafn2fOl9YqN0Ov8lAXLQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
