apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AtA8U/WsL0NmLmWzFtWvYaHhfUJ2hJy+yartVOEFwnZPAjOS4KmcquHNNZKqg95bRduX4X+1HgWacPHiQCoMtGy8XpaSPbO7IDgo5jfrZhs5sOcL2qS+4kxzIxpDMRlWzSXkncR4fl5ZVthrKF6WIBEVDa1pjodUv+OA+cwx8gTRKBAOI2U+dxN+lHKhvfwLFStaZjF5dIRa6n2Ed6aaH1zDEFoCrk1zHcqKIZQOWHFOps4362Q0sqtS9O/q9i1nJosjBvaQM4I/lAB0LHu0yQLrB1yhtZNa3RdeL6IA1HJ8LnLDtg93f9EkQcx2dcIVN5AMyfPfwa6YAszlLGKxZVMlAdVav+yDq9X4kswNvN3ghYnpGRDhTBQnaU5bnH1T,iv:cHTqy4ghHW8W4fDWxANNCQuLotnQXKLkmiJcWo5KG9o=,tag:6TBRdxegaxC0BX6zqEes2A==,type:str]
    identity.pub: ENC[AES256_GCM,data:aO6YV1YV9ASKZQSGR1igpvyBGzk6L6rqjyAJo43XoDi2mJPslf/wQgQpRVjDu6PiT+K54FMyjaeW+KjHCrMWl6p8nBKGmsv3IMzxaf17GJY5SpJBFpW3jpoVJWwnRcol8BeoJkADevFaRpPgLN7yLOBGs8YWzunbqPGpMrl5lhl8cTHD97srJO0LxBbAftqhyjOiDaK/OG5ZFWmI5L03pKffYQeAOl0gjauIr88kYlSq6irUlfRXrpeC40z2dFcafQFZ/wVyTv5t107I/Q==,iv:unTl3J9vS7RvZFAuJ+mh3A8bDDCPfAINWngj7FbcJc4=,tag:AWxLFQGElWqr62FfAwFCMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xxihmS/xQhZO7vfEcQtprP7/ErqZp+uRwAhOipysQC18S94PPFzQ1U+UuiFcUpHJQVSCM9Xem0YRZGHOyUer1xQqjIbfRWkOWloqiHoihS0y3TschtK5cxMwytgs0rlq5oLLKx4vpFTpxEYi4bxhG3zu5Qzc2IHVvWk6ZRs9cTO0qOXO6YklLLqVYDJ6JX39I0HMLxq/ARU6k46SzIJam/U6cjg4O0Xmp/Ta,iv:HcySf0E1V3ybdBHfJcKR2zsEMGAPRB3UUGQGBqRzqLc=,tag:oNcEybGIze2D+QgwsWrvig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYXE3L3pnanN4Q2ticHZt
            cDdaRDhvYk02V3YzcHpJR2k5dTdUZWw1dW1JCk5IcmxpNWpFUi9ySXZtalNXbWRr
            aFhrYVNxOW1mUzdZVFhyNkxiSms5OEkKLS0tIGpVbXY1aEU1ZDNtVEppVjF4bHRP
            Z1cxYjdJVHk2VVR4ZHdsYzZUVVJwRmcKrsxS3IMOirxuvtHvziJoYuXdtjitcHu/
            fcqg5PqJHkBHTWzfQ37WWYDEGVIVKg63FM9NoX7XlNyBPgwwDaOpRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:16:06Z"
    mac: ENC[AES256_GCM,data:1oKpn3k/sc45ZxN0+HE4GJL27hnw9/0Y6XYQ7YhbudAu+s3nLD2edse/fo1XQ+CUDel2a6JtYGwgGdgmHiE47DqBsgeyF0AHMg+Z7lkOK/V98dyrCFR29hsX5m9y+Pn79pHF7sPIYxNKNOHnwElasNeeFvF5snck9IlryZf+M7w=,iv:eZV1JNSh6JGGC06G4c1tP7ZUThlZFPmsgEuGbp0WXgI=,tag:nOLBlbx8NBdqBpZ6gj79Sg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
