apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OeYpFWr4qO5XzTShKLu9OcIashc951nG8FeSKWUqBJ7d8vWkIVZWaPEDVz859v9RM9D7uE6DbIuEq60eOopk5DA328Qn4sKCTg1WFXdoy1Ln4lf9hQcIXIDxZWTKxLyJvGwJQnwI1rGfkvQM6PXVArPC4PQQVx151QRlgqVRfE1sm1WZsIc9BK20e9vSvuWWRK0qSh0miZPSCsu20oXT0nt7uk26txfCG2O+hJjjRcReuV8m66VL+SIJVE8FUY92p9zpynOrEmPpsvi5jrNZ4nXynuP0r50TauKawUpHXqzGG7VsYD9CdKxH8JL8Bmo4bwwhZkyMyIsx4CpmmbVoRMBCLRLhsC+xEuILFo2XgvQU9JzlqMcW1K0Bqd340agV,iv:67eNulhEuvnPiAthZ/WKVnnPp/4Bzgr5SdLQVnXAYNw=,tag:goiQn5RsaHLVXzcCJAZGZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+fMr9Z/RQrsMLnHjo6kNW7lKjkJKvO7RdcB6RQ3NAwPN4LvmisrwTt1o5zMjtQLTCBBG1JyyHlXfneZOUsLwaGADwWqfcioImUTdtT3Irm6vXEwHzOZZOJpru7BjvrW/OfEVtR2X5sTSf8s1oXnDiVdWMhfcPdGJyDVx2yozl/2fNi0jvfyueRRgcoXMixkr8d8pX/Z6PtzOYxHs+Yl8737j0XbNWdkizQSXCng4YWagRS2FtG09yMwoYOaoH64aaWow9xaBUnQ1FHN73A==,iv:q0a4ZaJpL5BVxOTwH16/yTmYxkKkA4j949xzFAHiops=,tag:ofxyGeO3zSK0sizT9CQHjg==,type:str]
    known_hosts: ENC[AES256_GCM,data:UrEf9iMt5iPJ/uHWvNO6wljg8TErsORQBcN3mdmqeA9HW1FEjOwMrkoixUijobW1U+wQvaDrxxsM4DK9yc71oWyzfyYKQ+rjJPNysbjiGHM1h6o4tfrQs3EHLpf9T8NvTZG7k563dPhyb7z2lzlQcZa9kOFlzQXihKlwcPSU0Ql59B5bHI3fQKkbsT/u48jyztA6lrLzCuQDoIOF8rxlbwEWJ57dMmxZyIFe,iv:+4eUHi08jNk77uf74D4Dmza/vw8FuNpZKEv9hAM28yM=,tag:dE2hr0qF2ydNvUz8DEX+vg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2F3Z0RKWGtQUVVNSi9P
            eFdSU0JtRUZ6d2RaWEIyUDNWYk9WMlZFVndVCktEUUpDbkovRHBqZ2JNQXRNR2lp
            ZEFaSHdEck5HYVlDR1lkQ2I1YlQ4cUkKLS0tIEZVZ3RVQ3dSMEMwRVFSTVFZWllz
            MFNpeEp3TVFCUWFCQlZoRk53TG9YcEEK2KQy39MWMIl6CUyJ9Dq0QitSqfS6KXbP
            7fwTGhBRrAn0ciG6yBCyDrfmM1aZn7LcCBxt59e1bsQZPRleKlGKtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:54:53Z"
    mac: ENC[AES256_GCM,data:C82F0Mzr1qmzJnErRhSoVD6f6+LoMaLKc2mWxjjNcJD2Xx+A7UPDrxAY2X6yiWwHwK5VJVL0Herbc4jM8qCkRskBjdjyGy0z4PgdhqlrmigwSHWWLNVEku+3jkZpoOYjfA20vivRMM2A4bw5m/m+M+1sQoUTYmCIgDRFNsgXcI8=,iv:Z4+oabhvzbLqzPdYhtR8mCuw2XMuF2ZoP0Vb8bgSsNA=,tag:r+kn1y62oTxt/YxP82QHlQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
