apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Shf5XRPNQ8bBWUfoAnD/ARIR3BnSPSlebHlwrxzLKMgNa4HwrZa3MOX1DUngXTO1yFpY5Hy/o90zJsOs8MQkupY5GfgVBmCarm3Mmo4B4dXqccm2ZuI5AiwXBxOV6Mg3gBmaZJNSoFptcQeUX1ihhd9z1fjwbi4k00zbGH20NXq/zXAlob/PQqVWOwqX9di+k8W9suKBRQY/QlCy+1hdOGlK1252IfL2NM3YiJZ1jSqxOTEsIm8w0nGzapz2Ay9s8/pe6zGusVB8XSRGq05W4ZX6U5VzEHEj92pDoeGHysCXh9N8yosyypWtk8py31EBWiW7cwl5cev3nJIOSLRBhRolSR+cjcWNODsO8tRizTyAc0rHkprlrmzxdLtaLXvQ,iv:4/OkWuKSKtOJ/7Z+cPTTu2DF3ZftywtxLItjUHII7Gs=,tag:8ruWG6qrzAlZHB9OecNOqA==,type:str]
    identity.pub: ENC[AES256_GCM,data:SThCyk+ekV6oMfgME8DW/hXVaFDSQToSlgiKFrbfgUZ6W8D93e700yEL3DblPc0Hrl6147mMyeCjh5mzsx3JeIRGr+SpjwOU3FPkNY9W+CmI9S/ECShm96Wg0IGvKimE71OlkjUaHiOmeypYwcdzAir//g9rT2ryHrTZY946k6ybcL/t+MVEwOnJJMwNQCQI1fg8K/ok5iY6p//ColVduylWJ0Ml75hzB/qzmeQb/W4bh1hXVOo0lmPZMCi83KRi5TMlXgknph0QgvXHog==,iv:r2uVqhllPOE3YJUWzVJ0LB6NPQfEXZGaMbBBfDStOw8=,tag:41o4NzWCwla2YIHCQciv2w==,type:str]
    known_hosts: ENC[AES256_GCM,data:yzPnywdpLddRDZVj/Zt9Flatou4UQNrLF77DZ6K08/Gy0WsVh6BnL6yc1S/0DI50rMFjWRzGidcvH9Ihem7rij159+vBUTC7u308arizgCTttgWwdK8EQJ+XunavTPc54FPmcyMC0WCu194+xbnDPP9ij8mOIhwIZQu11idaPcPFXpo+0rBUZJ+uIoEOccOD67OJRE9UBiSVTWH7w5WEeBXlf0u5hQbNbKSB,iv:i5+FfiDPg7e+HDkO/YhrBAjXtGYmLm39UL4NxfSgmfA=,tag:PcUtzB78Hr+TaIOg7UEIMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdVFROER4YkZ5YUpxUVI0
            ZUR4Zm5PSGFOYjBXcjVHeHNiZTBUZGU4U2hnCkRISEhLSFUvcjREckphVmVwMXkz
            SGJVWHNjOHYxOEQ1ZFlPVmxPMjY0SGMKLS0tIGlyTExWTGtqUGV2UGd5WFBJWkRF
            dHdxR09DeFo1QzFtbFVGazN2SlNPSDQKVoVOOP/YAVL6+ud/8vVLOABRFAa47BIr
            1B4yZ2A7/S0oA2qalfBBFcObfmt5V9DqJCx80awSAhMjYoOv8IzjaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:30:22Z"
    mac: ENC[AES256_GCM,data:KRXzaCpqoTkc7mwQ/eXaO2vCjKgUXUgW2muBOcxulDfCJ5p/HsHL8hsC7gGPc6Pm/rhs7qw9qRRvCnKQBb8XJce/pKd/E2V+r4Wq6QgqDc8/G9xtlu7QjYtI/MAmXMc4WE67Ibag5aOl/W9uLvM9llswnNgfVED4DbEOhM6Prl0=,iv:254iUITvs/AG5z8AzH/BNtigoCoVvfy4/ljsweffUtI=,tag:IUVeQW0G7w5QkPfINvD0lA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
