apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Jm2U2qefWUmw3VlorMwJkk3f+eZgn4EDbfgtpd2hrW1awYR1eWrqQ7cQIfmq5SpnDC+uYT+e32EVIXxHVwtP6oCgjN4Wip8XM62dChS39ne58fiDmx3JyPTB0LhPh4yEcJXusxAmArD1dP+Ya5MQHa61MmehbyPvZmCAbrpBU/hyR626CfalFvWHMXSjQKK4clvJo9r4IZLdgOMQHQnhP7/p0j+aAkeBAD65KFEAh9ju7fzMV5cE3qVfifAp5XQDIe3WsOXj8ONs/ZKkCK8USRJZNOVhgQKT3zgRaPk9jdnvEXGcG0CjIXxccoM7arCINXQQqBl2U7LzE1wl5cs/bTh5IIL1f7reaRcj5+zI6wzq/pj3T7TsdtQbL+fr9zxb,iv:T2VjhDRtcDQRg8j+NTSs4TOhREbNcDzpK/14dC7s9HE=,tag:YyfNn3XjkXQRLSR67sYolw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JOOjcqjUQoitPDWTNx4JOeix25IcnmJbtH1O929AsiO+QS4R6S5r3nMMdeszxDsQbzxqtDL9p1j2xmrNks9hlS0E+M0BPN0XSUVitMXtKsGfjiOtkDQLn6Pj1B1N/oa5PZ90hBqKJPkNv17/VJ1jcQZq3O7G1Bu/85x/0S1iV4CFg3AqRXHSQ7r+z06JAkDlURI6ZiSRSZSsaEfyDH8/qGh2RbTnOqNT3kffcitKQeUJVhJlKfp+1ELY0gFp6HYsfQ0hIKZYI0B6/asTwQ==,iv:/tCfw81MbSdy8Uc8XrJtmMuydgSceR2+CaP6WrSI9ds=,tag:DEaDKrpRNKjlHHPLNpKlDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:oAEKhC8ynogDB1MQ2kxoC9rRiImEN8f40Ue52QCDeUrOxHUCtAzRusSYmWsX8CvTrHgXLQpYvrpZ5K6mpGs7tytZ/qFsBcBZFzHOlyNBt6LP3fmcqeFBGZumsMpvTak9qXbbDEHLvPdNEtQf+X7ny37JjAKKBtxt9hzaLPIuqxSbfIRuj2Czz7PwJJVRnkNyTv1FbhYc+JPf8Uiq9DLecxf6ECOL6ltxFPK2,iv:eApBYfEha9ifpYDr16CO/Uq5hXTxWYUBg9tio+vt6II=,tag:bUb35OlDNfGHglKR39gKMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WVdlZjNZNHdTKzdOYzhr
            NllZeFdMQWVJcWpaL0xJUS9UOU1hb2I0YWlzCi8zUmJkTzZ5QlJndjA0Vk41bDZw
            TnBER1VqaTQ4UnZrK2JrdGtsTnhDNTQKLS0tIGpNOUhJcm9ES3FkYml6RUx1ZGdI
            V1ViaUxpaFhMZ09SL2cycENWMTY3U2sKXGr9b+Zh7J2jB7FsWjWs1aStcKykhpg6
            W+jWYjZhP3jEFop/raisbPv+KbzY2y0H4YQSHgBFIfLfOakj6rAp9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:25:09Z"
    mac: ENC[AES256_GCM,data:M3AUoU+/mFNeL9fs4H9kHpiho41SlbOKJXS7g+DJUoHGT7BhMWavOiwF+Yiq0IK/J+0u3CMTUgIMYpvt4VOGDVb9mPuyX64rWMMYSpOcjXwNMZ74W8ul9WeiXGaTf9WWrAoI3WuDjdY3MF+49wgkQgC+WCoRHMVuvJ4fnpgeAtA=,iv:jmOf/R0xsFj0OxqlAUatgjMxE560neWMjy0AunQrXSc=,tag:YVAyqon1gzglmywLyx4gpA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
