apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t1xx73OA/8+YaFV/Pam23CAgLhV5U4/wNO1BE4wejaoDew9ZMXtqXR3DheT1wFEi3dV86fAznmBiDI5iU6lFdFxj5QTs96AzBVzO+uZfV0YZNwQgiEpkK2/lpjCcvGHpOZHNqD/bcXy7+V1q793WoDq02xJXfa2SNUfN7XIjCftt0BALrhuwZme8pDSX0ucTj0lYzuVcfdx6DWwomQTiaXuuBhr11xaSl9oCS+seOfQrsIBZKO8fHp1Lp/9q5UaoTcZnENyQ0ZOdmExx9wTTuSL0smcX6+hjHWQ8Lwq/ZVx655xl+8v1V98HUvvIs/sP89oNr9wBzGorRwAIhpdrhyYGUv+NW9UrWxzx1/STrB3IZeCSid04pFMClhKpi2ZA,iv:6bPIT1revVxFqvNPqwWntEWISirw/b0FQfLjT7Snux4=,tag:GDsb4X5iAHRHMcepu2rZ/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:k+LG1c/HssME4r7UkqirlkPKQHrjqe6YtRAhC0KNCvxCXjLXzFLS78aafFuSxuPhjM7DIMLdr6XRW6Uzj+Tstf+CH5gTRn+W1dn9T0VnUBOGeQcVzOFRZ6KrTsmsHxYV9g4pLQJax8XXYMg3CfwxCpt/Jsag3r6GdgYRFf62tf629C3WhZY3mANq5KIZ+khqjKG3SFnlb+vj0T3ddNIwreLx4ryRhyO4Smu0uRithtJ9799Z5OOkywGyOPMm+yp+KG2dopRFBLH+H7n2hA==,iv:mlVT7kBWwnJ0Y6W5fuUxhEevTFHVuuNknmPj7sbQLe8=,tag:20wORkwO+O3wbfuAfVB30A==,type:str]
    known_hosts: ENC[AES256_GCM,data:0sr5c8KnO7k6d3khIRhEisCnT2DW3KJls4KbZf2oHGhDw++A4FVK5m69YlLuN6rNtP+0lJZ4OXwCMX2RARYVs+3cDIqhx+CALzF5G8SDK9uh3zkiRQJDvM/4O9VtKdSdNiHGNrBMgSa9XDAMSmcvbZovpV4X7MeOpVhYlhe8Y2UPRPSPZji95LhnR+W1HWgkgq5bTHXYTGcHttoV6Pg+jdaZjhl1qxMiy/D1,iv:qE3EHD7WVqDrOc4Wo1waQjo9qIPLI9TTtnl/tzGstDM=,tag:vUv449pkd5oGrHGt98e4Ow==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaThkZUZ4UnZoZ0RPV1Mw
            aVdnRWcwL2dJOGcxSE1semtQNGxZUmxsL25ZCmJBMHUwSmtCSkhFdTRHV1BMVDNS
            ZU8rOUtMZUVxZ2k5VE42SzMrQnNOcE0KLS0tIERxeE9BWXdVLzFPRXBmVmlTWGZQ
            dmEyK2wyZXRQeCtXT0NTcjd1MWNYL0EKfD6OK6PCBlXaFXjcOYKEhEXVwLf8/MQQ
            ajHMcxULbUqQfzHk7Nkom0kwwNf3F3ZdN7UeTvShr3khwvG2cd69iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:44:43Z"
    mac: ENC[AES256_GCM,data:ZejlJhojv+FAMZtqZTVYhdyvKpCAWrL33kGK1EvrjAzn4l/J9xtE4rXRyb97Rdsbrum0FNVFbF7h5N37GE5bg4pyyy2yDLJlQKGui6vj6sXNESDZmntwMRzTFm94hG+oDEDNMkl5iU6V+vifMdYyfmtCKg5UhS6V2XlssySk7i8=,iv:Nf36bnPpmlC8dKGnMF2uBD7X0c5ECuxaGTE5urxgX/U=,tag:lEm6+1kR8DVVQ7zRdiGqIg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
