apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+H785uGh5A6diSExLfFeWzRY0ywLai5fPo8MMGcPFstrQsSwPhHx4cpY0Z+c2P0LWTTExvhzXEHhOBYwEnSBsMcirDGo92+pJlULNFiJevjm7Ln9KXXupT4+MsG435OrN6fTzqFG0XvS377ZXDIXn34Gcv7CZR6Rcyonu4HqG7jFiZZtUAT/CbMsePajMEqW4IFAl4U/ORZJsvNwxCXs2UEvufWCoVbwJRFimr65kWxegXe6ar71Gyl485F+Oa/TbiapI1jjnde4zsIqzfjvzzsssW3m8+zjZv/+I8P/OGPP9wOw6FY93hcozEPD98pAOHi46a43uW7umJukr3dUamLDM5aSqTV0lzF+h3y1acWW+rt7Bhzl52oZF2yNPoJQ,iv:KtiV/BjjiX5pg3AmTJdSzOOq3utRnnnaatwVZ+65/0A=,tag:KkFE2Dj8rKLJpP5XvZem7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:D6lrHUucGArtCjq0aX1nascwqPaCquVw8wSiF9d9VYl0zQ6M9rQdkYoiDBA/pHXksy93G7MGBM+/lwr0gGNPJpvokQYjwv7VXFSx3U8qlMpkzIESqd8wHCsm+kCcLcdYf37Vx+qfp5dwqd1MJ3nsElVovrpAfH247XmXfmsX1F0Jk7p6d3h3y3d5BKO5ukh5qDURhkl37rl8troGXI7rUKlh0Sam5U2NM5WjprfLb6y9FMfT8HFg3mJHsI/I3/ELkngI8sF774OoJntiJQ==,iv:z1GI6nKCHNvTnwnxHYKUdK7NKSf4qo/OsOPG/umu9sk=,tag:KrWxkbGUM2URHWMlqoBOiQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:B68IHqnYsrm8ubCRAAbnL6Ra3ZOGMEyGO+e7KxuRsd59hA8JS1287FbNR+qeLz/3ysAQGsgd9fXlRJvIQUd5tBOIwHNvFs0SgxHSkY4B/uF+/CJ5+O152SzRqt/FqRxyrd6+J7c8uP5YTx6p0ARH5iLXVpN99JYSBDwRl/WOyP3+gy8f5xf12tdy+asz34LbbqF8sdCxNXQGWwHDSECPC8bbIBprv3oI6cPI,iv:P4Z/Uk5Apk6S12tCF42vMFScv1Facw6MteAwZNKjuok=,tag:B16YfZ2OVvl3DvosyV1+mg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL1p5dGtBYkliZk55UW8r
            dmpUK0Z5bWJTZWY5NmRuU0YyMVdMckpjWjAwClY1ZHNpZzNYUkx1THFRWG41SHV2
            eXdFN0RKVWVzN29XdlhSWlBWZTl4ajAKLS0tIGVXamlOTHFUR1hNQklhNE0wZnFD
            Mkh5WG1QYXRiUmRYL0E5SUFQY1JPMEEKxZTPUbCRX0+29TuICPfGy2uy76vVV+es
            Ih55wAlgCPFqKkKQ1Z16jT5GHrlmk2pN1l7KmtNoXPrRvZTQVwSAHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:10:16Z"
    mac: ENC[AES256_GCM,data:uydY9GYilHBnYCBhF1j/misYkI90AE3zSeA1LLE/x/QUM+m2t1AA7RMYnJqPFyuI2MgG38IPQ1gKq0bJcY7AJ17Rwss1M+gjKpomcse31YXTk73aRFwvsQwANnpV+CYH03f6BsRatzOT4d01ng22lyOknnGt3PQeZAoNS7ThWgM=,iv:qck3ltjggAv36cNsQl7utrUKFmc+hxTfUGlBLFopfDE=,tag:PUyUKCtHKjCEDAqA5kPrLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
