apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:noFk+1KJ/NBmkbf6zwLH0SE4g83H4XK5uLQIPDjhTEZQH9dEMLnhBCOGtTkjchEYQB3+AoCsbd9M7Rx6taTgGWRz3oyZobM8HbaVP6QCi2lTkFevDQWLIduqCnvCK+k6ISc81BuJep9SE9q4IogxnftksfIsg1iwDuucVxIhG/coqyQ0AtXs9urZXA4G/jj84OHir0k0o2V49qofEaBKFRdRlx5ptqQFnYeN0UMPBcUEVRjcAxzVuJZe2Ua+kYICBYEg7Vz+i6PPmOYeEA2kw5yPF7h2AJ3VW9Es7/13J1xzbBeErxCP2bvdR/PfzD/bAUi7+Mljr/zcJVizah13GRE8K0TRjnUzXr3eIO9xO1zd9nbaP8MOTJtllCY6baxf,iv:HAvhFOcYZrVS1+LiMLcf0W75G7N1A7473LxX8r+9kus=,tag:IHSCHnvn+vhJjWxmrDumrg==,type:str]
    identity.pub: ENC[AES256_GCM,data:oq5T1QABE7S4lQuhC8+yXFTJ4VDjCfgEOsRiEwnICWkvRBh52A8Ze47fVbrTKAkI7uichjagvtJFtvA92O0oeGXKJ4eIup2l0/St8wqsAd6Y+XIwWwAXRNmCCdfDAT6fYj+6rVnfT7Is/D8lmXf8pK8XJWr2woKu/ji3ARJP2mTgEq5RtU7SeLzYydWhrcFfSvRCDgtKBU6pVqeAs7L2oPVf8JbX2ACVqV3RnA05upzm1WunPFs4mnw7KcDxLMlBJKtEYG55S4ROb39AqQ==,iv:kZ1Cj+dK2sVoRHQRa2T6RbzlSw/uMfbHU1b/6VXsjdY=,tag:3yiGpH/uy4jkFAJ4WMszqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:UI1SRaLYdkcDo+A+46/Al7yiSo+Zo7pJBuZvk04XUi6rfLhLd4jcSGRaIyDeAJelvvqxsTR+1BZLPCraM8zanxXI+LSmmeMU2J4d6GmNWziph4VK45gNXiDMm6yWk7cVsLhi1rsuYiA51kgdc9AAbCA1dXia6E7ZbrBpp3XZ3Cp7MalvULRq4qZ0AgvJhIKu8W29eqHJLfSvZ7xGi67v4uvTx8JAUmI/yroK,iv:3Xl9jk2lV4bX9nGKMDDi5U/wKN+4bOgFgfGUNeY/k2w=,tag:BbQMGFNBg2GUVo8HQM4JfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUjRWQzhjaW9hUFRtY05x
            MFBYMHVOdjh1UzNpUGI0Q0trRlI2MFlHWUJFCkI2WWV6d2d1d1Y3akh3aGI2RzN1
            cmZyT3Yxd2Z6aTRFQlFjN3RZa1ZOWUUKLS0tIFR6Z1lLWThkRlZ4LzBjdnVoVWZQ
            eCtKV3hGNmVaYUs5K2Z2eDFyRjZLWEUKXX/1baAp7YnY5Eqpubi6QSn/XxdqqT9A
            S7NTbVHx9uvKc8kFMYnyXlLLxU47/eKjezRKZv3GJa7LTdVMSXumrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T23:11:21Z"
    mac: ENC[AES256_GCM,data:C08BPilbi8yBOe6KTd9bKZCVyNm33GbkDLZPu5aX+sK40TcCikeHmtXQDZK8Ezdwm/YORnDoJioukq7fuJPGBTMXZvfdNqRwp0PaCK53X0Wfj8Nu5FtQtFxDhFHX2DafCallIwNxUWYPDccEnGa+nUWnK/zh8KwyC9LVrSyGC4s=,iv:kRN2MLRzqh86gPGfmuvHQra6fTazQMI0aaufkER6fCk=,tag:JBDqh9z7/WZrcUyzubw1IQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
