apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6UT7TzNm1zYN7codoMSAjC7nQSbzmHIAp6XfNBxH47UweiNy7sEk8Ix6efK3eO/fvQFypwV3CrcFV2IxEZcPwA3a544GRImgHxbT2sqSfJXq4Ih/QmGEhT/tCsK8yaxYmKHCJzZynGiyeAVAA+ni0kGYMrPihlPrOPT/xbquC2NSjHTNQ6BkSnzAWicc7lbcRsAS9b7XJHfLBLemtr9PC8ozm0sISWRQgbTgDR4bXHuAADHYCtKEI9tb1DW2n1eXeBhfZui4KikFjAOJtXX9xk94irSDYn2CEm5Xoqq5npCCMTI0d16IFeNMaERiM3o7NWOFXqwaeLcubb3gMHjxg/Wl4yyjiyz/v8gfGU9X5mwbywF54wujnLtkNuz1/s5S,iv:k17y0RyixqX7pHGL9VBlcfpAS9Wi5gpy/w8er9BZPv8=,tag:LNY4pCajFBG2oXpOy9M6yA==,type:str]
    identity.pub: ENC[AES256_GCM,data:3PUg5627zaCRQUF7vxy+C0kbr7MNaFhbutbFbWa3Dn1ELeO2UW1FBMUmSPvV258lGEitsE/hh0dxczb///DYU/JMe4lSTsxQ2gNVxIUZtRVev7QPJLB8g3FU6T07Sg287bkYK3LraEKnkvM4h7L9xbCRkpYflRkmQXD4JGpR+90BrRrlPnz66D9t8CON0aXRU/Mzc6HBCl5x8V93Yz79yuyCMg9KcncA7nhD1PrfmGr8w5+Ygl+DE5Buif48lh4zl2oes72hSP2FPmHt7A==,iv:rQVnVFPFql+hrxhqBv0jxI8LARPia05C0N2H3zOwP+0=,tag:mMOlTtPDakxQ2wq851keOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:GdIQ0NEJywtwLlWeyqlILxhF5avlHpoi89x42cYb05wnQ5h7RHxClI0YXO9q39MVaTO99SQL+IJxRD14942SYT//7uJ30DoyNPtNduREe7cSUhx56sKm98HGWsOiFE8RJjAFwNMuztmIaEZv/QluobX9SqMPMXEvV62i0C60flRH679+GS0spBqyX/zI04tjQvpwM39QZx+Mh4Kpp92DN4/rR6o0HC52B6xY,iv:kZtMnUzpEt/emmfb1wY5kjVy6Hy7SGb8Pi0ubVG5dw4=,tag:sYaSzwEwSnLL6PZdNI/UPg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmgyTFlxbTFvOTRmMVNC
            eGt1QkZYa3F4d3FsOFA0Y1dUaFFzQXVud1JvClQ5WTROSFFhYWp3L0E4OWJSQ29Y
            RnhjUG5uNkdkb0hIbXFvV2Yza21qWDAKLS0tIFhpVjJidzdNZm01Y211QVJ3RndS
            bFhVZjNCaW8yNWVvVmlQL2tkTjVhNGMKtJWGb9cLcs8hpVldrmiEbeBPAMuGOsWp
            Vguqk0VBwnc6E8KX8CvXvYh+ejE3Ws5CyW9eaQPczNy0KHeeycrp7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T20:50:13Z"
    mac: ENC[AES256_GCM,data:oycftPfVpuyGqO8v81wZSNm5aaLWRKVtkhU0ZFT+NUTagONOXi267r9duJItmwUmIuw/FlZslqbh6aNStKBLYAHwjrXweVThA/lNmo0FR16W1sYoOSAbg6eJ1DDrz9AlP6wcsmr4f2gBDTN8t2n65CGPcLa4X1h6R5TZLKWvwvA=,iv:nK0dG9Wn6t1XL7TAmzEa+sK1srY9/k1eyTcz7WvfeAY=,tag:jVroMlKing5fgGqWg15i8A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
