apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ybscrkeKMhjXrEfTPa9k/n0s1g5LP3PHxtgyJIwS+BAOP5dbh+8+S179lhjsXnSCR2lKKRABMs+B4ZIpFa06beZhye3PPnnpBwEsjtQfBqQY3rBDtXbXmFUoFIF3Yp92IVW393yoqKTmALCLRM1DdFsLNB1nWPZyXB0sKjw1dzaM0+wIcHfJa2mMpc90pPjqKLkNB7nly3gQn1072qe1D2sn16aZ4SUcnOyeofffxmmXgdz/9kK9A4Lw0dgr/ksG2Fy2CIhJgoFSjk6nzYAf0wBzCa+x3tyQ9SmlwW9ULUCYQpbFMdCpQz/nbxU6YVjHmiJsCQb0MLvdqcjh+euyMMMUiuXoka4lqv+ULgmCoTSwMorqazz2lWoGffS/lY+a,iv:U3BmHYaH9QU2Tay301NHoc6ff8OJoMEXMrNymJ86sAY=,tag:tm6ei//1W6wK10Q2HWNrkg==,type:str]
    identity.pub: ENC[AES256_GCM,data:NsmVOLGU67gLTNQOvhJqh4dMCKL1J0S5ZwDkNO/IbkLXCOInZ9DyFSmxVTTsHPBYdt1nEaHhIRVani2m5I5vQH8L3EP4w4UVSxulQR7FnvBZDV2s4PZ4O2arhLYcutByRuikfHYPY5NHDx3B82vOF9lgrLBpi5MOarkgxPI+OAPzYZzfYV2i9sNfR71bl3+Nve3VFVMk539A8bzHbvc7p7vuXboM4YRtQhPUO2SZLBdW0ItYRFz6faiCk50VLrlRON/vgaU5AmhB+G5YDA==,iv:+JQjaki1mj2Kha2XsTcNBkVnwitDMP89WHmezeEcKYY=,tag:Nj6DniOfLEVm7uKpJ2kFkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:DZYx+w/4ea7yidJypAq88qGQJICdK2kHWCeosOTVZ9o4YE1TAAoGzjqQs1+QCd4/oupzyzAxkQnPmfhEcrOXCD6nHVUUrT4+Po27eEO4qD6ju9keo1pWLptosUQ+OURTb23uzLDcBmFgoUprQz7j0/7yrFCj3ysIpd2RA8WcxkNNCPxwur1JXbwu/LnGoXIVnT1/1fYBZt9f2qFJU1l7RMGXfianbqWzZ7S6,iv:y8GXX15575ZSeN4sWuQ2FsmMg7W7AmS87WX4K3WPTeE=,tag:1SwJ23qk73krJ+RteG0ozA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaG1tMlV0WmRPTWhKVmJ3
            enYvOWhremp2cTc0V0FmRDcvQ2lVcnlOZ0EwClBrRklHSjUrR1ZoZ3pCYXBsQS9n
            QTVPdi9JREc4dWlKVFpEMXBYN1dXNm8KLS0tIGhaeHNCZlY1RTBCNkdkeXRqM0Rv
            Mk8xcGZzWVd3ZmV0MmI3SHgwMlI1VGsK2RjF5qVV7kF4oO0R/wUJpQirzlHKDPkP
            JUr+Gk/YrC9+FWdaI4iTWLkW6GessDNn7J0R34JEGjmIYs6hkLfg5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:01:41Z"
    mac: ENC[AES256_GCM,data:EXPI3Snn1/YIelUi/wDUwX0fYQ9vBoUeNDhJUB8OkL9GtKTHVAzr+eNN1jZM70stzy3VWS/Hmc2MZwTHLE/YWaLxm0T9MFIREygQ7u2Sz6Tjyw6KMeJMYoT13O0ZOXE0ZVW8xgaYOnGoIqNOggfiZJdnnCphgPBl9psxEu07+ZI=,iv:n2wWfad+9WPcmQHTYwucLJcCF87b0HHoEpXy7d0jDgc=,tag:d7yF7u7D2Dd3rOWudiQD4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
