apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i5+5ENmquZZjxIBhrFfVPNW+G8cBdqGqqYMkkQbMrRoxnQLu6SCvGsvxhEy0rHeBHpBOGbnnlkkI27cvZ/zyj9TiJ8k9CdGkmD4Q4GaDtcWT4AmTT8gquJ6Hv0tY+Qm6VL0H+R87rgv7sdCaw+AP8ULxnBZh0s3nqINNbAFq+hnQWmRe3/DOvmdQ2ofD7RFhBGMWoJz+GIxEjxWkR3YDi34alnVy9ZbkwfXn13XVA19fT+9n6sbVrbyuc8rvuS14dVvmlgSwyHMiA7pVBVVpAdsuYzg/fcJ55tg0dJo/dzHZ9YcCvtuxFC7EhYP9LaJU+8bqrQ7dyIEr/ksqsRXDSLUebMGoSLFbBx0mGV2wo4HJiLGWdIi8FL/1NCGpraCg,iv:/Fj64ZytOLqzLwJSwosQix/5psCCbFCWRDCXzv1Gvu0=,tag:khhejw9I8Pvrwh7W2KnPQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:mZ9RGO5gSd1qLqxdoI1yM0ptTINMS5dj/Gmq8+MaSnBwX5X7rdf/LkI5jkX9KeCWDebRA8z5sFGqq/fQJeFaJGJ9A0XhgTrmQEG47Y/tm99+cWWcwAKzUxkBq71iP2g6oPwlduirGwdcl28KGA1nxEcGDa0RZ2xTjsyBFudcq6+mJPk08wwQBOV8Qo5cLLw2Umn+a/6ijR6Asw5k+KwkN3xNFSgmSaOkg3JJ48VAVZOZQFrmhwQZymPmAfGJRGkFFcu29L0jMh7KC2xcBQ==,iv:BovBK/acvBOlh5AJa2EEeVkI37c6uj4QM8Xa1YIyvN0=,tag:OneoN1TWqnvkkgMQ0LidiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:6zdiW5Fvr2iKztnpX2pUDDiJvgUKH77oXs8tDIQy2eDFX3Ke83ascWUigPKr5QgZcWvyTJY+VdMkfQPcRzAmORV5NcevG/1hf1PwHTuA73yFnpWqoEmct58PWJdx/PJ3OcQAnhvAxvBNVZa9/4MrMJD6VhkusBNWNzC/5FNqQlVaG+NJmsorlPDBsKFjpv1UcBgaL5KaJ1AdgcFU1Y4cV0ZKyjW/gtUMtBZy,iv:OBiTGM6v0LM3wvDjXxzWDeLXpg4lsg0Of3JJDR4Hgy8=,tag:wkAeL7APO+/9HnMEsrQ4tg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN1JmL0U1OVdVajZtQjVZ
            dTFKZ1ppTXNCRkt5em1yTXFwL0Y5UzliTEdBCk5pUElCUXQ4cW1PRFR4dTd2bWtt
            UjhDQXJ3VWF6S2tYbEh2NElaTnE0N0UKLS0tIDQ2S0JGNk5jSGtzdnZHM3NYNU9Y
            VmRZbTNKaXdwSkRxdEp2T0dONk9pdDgKD0QHaULDn4K3aFV0bI4TsdjEAHmEpyKc
            LM2R+5bOggNFXuLJagdec0ESEa00QOqrdrrtxJ3y74bLznJ/dStf7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T01:56:59Z"
    mac: ENC[AES256_GCM,data:aBirP83fZGI8YaRdGES3WfxPO2SF64e2BtByKvfyw46cwCl1Nyl4IM5aZBNaMEperoufeUOsi1zoBbG3AXHSMs/YqMod3hQgACBvVZ0mLV48Gf5k1L9RSI73hCv4uA07SLDYv+lCoOA5lDRiyec3J2Bi70O55S72fsnaWwoqf6E=,iv:pYcbzXp2NQbw4Dzd3XfDwxy2HMyEDSLQ1/cdUrsAdB0=,tag:yeSqX2fSf/MM84xFjRlLNQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
