apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mvLsWBlO2dWp22vvxqDoBhn2g6WmSIQ6hqFR9Ly77d630nz5RO8Vpr2X1pdqtuZoteEf7tI6TH/do9mG5bDPbTgI47ZnMsOdbBMXuaMV6I5ZVEdYNJjOKnBo3IGtETD8QSUcsHZ3CxjZ7lgt3Fi+B8WpweHOdvRDOQqWZcYvru6tcoh/YjXeXXnTWDq5SnPd6Kk0EOWWs5IcrLp7OkZdjhKd0r+K+jrPpONdJq+3cEW+R+kTl4lbzNIxPKn58vgPOGxsUD4biZfS9ByC4afUYVfCnR+8tZiP4hFw2+8iF5tdpjpBz+bx82cvXyXPadyrX47Go/0AKEXyhaty7l8ZIWoTCgF3x1GbaFEh+edIPjPqDYbMQpAoXuVTY7JW7fRN,iv:D2/LAC4EqFsWL/9XHYTemcqY3XC5rAzgWeyyHn7E/DA=,tag:8Eo5XEcBJyL1rAuC+1vg+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:wXpqIJlpW64KKKIQG5/dgxUk84Gn54ur6EUidQFmurQZMB/IFBgHDcaOWB2mZZA7BQUCRzc6GSYS6CpsPMjBPdhtjMP5IXAmUj2A60TR323/L8lus4cY6x6S7d+NrE7cMhyuV0mUmot107dfEKaUye9cwmU/dtf4fumbOxxcoyVhuQ8F+BF9d20v3QURuihDppr2GROYr3KsyCbPZSWprHhRJ0gx/zqmNHmzFO5rqCxX3vbQSahBFDQEGwlYU6dZPc+t3nujksFPGWyg3A==,iv:gpCvcl6gh+lIHpcHBIKlY6+Ip/MuZuqodHsFFfZ9mYk=,tag:kfXIDTXRZtYfaMJz3/jCyA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sdjIGR01aPINQR/B7J6545QCGsLVeryoptlMZ4djot/5k0ynCaQfl7cvizdNF5nVfvo+9G9JaGnYifeA7AvoXT9I6hoMHenCIN7BIIWreDUbSMcGIngwmzgaCK1zVcP9mh6tydmCyEZNkx5HWPv89gZnWPVZ3DfZEs5U89gTW02xCyBa1ApFRwvvulSec8FmNNOmvLarBHk45u1zFuJzOg/RYVvC1CQIJNdy,iv:o6W3jCV41Y3bclwMVWc+GLvtB/QtPuGStr9/jXqYLy4=,tag:x5xewE1Rwlh67r9lq8ksgg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0N2ZEw4UVcwR2NBaWow
            OTNOMGlKL2Vkem9aZWNlS1owK0NlOG91MWxBCnN5ZThtWDdhTTN2b0szc1p4N2dw
            bGlDVkxCOU1PU3VNOFBMVHlKalBQam8KLS0tIHhDc0NHVXdad3pLQnJqR1JxKzN6
            Wk5FK0EyeFU5RGp0d0RocnR2TGNDbGMKzxnGcc/Se1I3CkB1VjiHONMiM/RtdNbD
            DjHnxgTAkoYKDK0Ae0+C09l+JVk+b58qk7VrO9DnfYSekQJbV2ah+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T22:41:01Z"
    mac: ENC[AES256_GCM,data:Jb7nBrOUck7lxz5D1qMqy+Moj3hZKf/dfSA8hy1hdOTQbFONiIm3YqMJ0W4h5NZXjUydBpqeLJGBOwuXDmbzT0P3BAYJRvtmWA82jbgkVD7uQx1SCaXsKojV3mjJ11+h042aV52gzObY74/i4Ta1ZThp9XpPf31GQQzeGLyTrZA=,iv:xLyxrRo/Xk/ng13tAZIhSKbX8YZPnPni0t+rgyq4tOU=,tag:XX5a5D5xwAOj/32shV+o4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
