apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Gx2ZzugmUyrw2DxukymS3YrWnc4fJPoDSyaluNHYM3ANSBqgv6CTWLqPdnIugQs5KbrwUVFeHaW/oDN8BnpCn0L15GRphz48ktikD/gFUFGuaEcW8IyX0DJd80F85T2Q9ji+WGtW83N/BON9oS7DAxp/lj2ubY95BFypInBclxDPhPKwzg6IOsvaeOr5UvvSxgxqD4VzbiB09D8J/exiXKwjyEaaqa3osOvc58edmmESOqoL4ykJ+aCzCo1BBdXg/qiHS0NmGXc5izCm4Yvk5kS/ylfk3xsftAyZfMOh3d+VnnyXX/uYUUxE1FScmutq6d9kBCJB9m7oOwx8Fa0x3t/T7FAxeli/T8xXMGAzyjQM8m40vIyZQhMrlkLhLgkG,iv:CFir3CYBGnHOq/+BZ5H1DQEUyEH92xUCxC6U1lf0V1c=,tag:Gx9OuT5lhaLH+aoMvNx+6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:iAZ1gEQkF5sYl7XwPGyBBIZZspaUoWn+0UkFyu0sB/6Hy2dM0au8UXxs2DsOkwTNpBRhe6cFMcDRKqf5DsH6UpjL+P5kiz+9riuhAqPnRc2nTnBZmop0QRnNCtp9657fMUATvsYiCQfLWBO1MduG8/Javn5DlZw1ex/LxuteNSQlWHqK1BHccvFc7edF/Edl1ncjt69Wl5sgwX/UONb5DECd4WU8mHnSvZiC10WM6/Vs1fwIWVgYa7bRJ0H1IuN13muW5z4mreKLbIvF5A==,iv:BcoF/GiJFJQXYZOv0hC/CQWWgs9CsuPEPRJVOjykBM8=,tag:H+NA8FNiGEVaTODAx42TNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+/k143zhsQ92Oapr8HWJ1oFIPh1kiTQZT53R26ClCgOw6Ab6SeJqScguo/a9q7Kru1yupUK1DFfXm1X8qPjo9cNoRfHdRg5wQwXyhhwoFZLsEqijNDTxidujOLzrPpd3qC9W6rz4qir1ICeJJczCd/drO1Q7Gi5xthnFnMbASoH3ClALOrxStU9DfAYxTcXJkPq2Z26qFHeY5dOx5kOAyMxO3v5b92sg+XRP,iv:mkSXBPEVlD3e6ibl2OOq+wHdSGC+GeizRC2E5IIJgiw=,tag:ybYu4ylz3HJlAI/n/ZUMnQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZDI5WjlXM2dnT1BUclBl
            UGg5dThNYUtONUQvLzcveGx1b282NmhVdG1RCnZpWEg4bjAxLzJhdXFrNyt4OVRi
            c0d0a1c5UExiWnFNaDM0ZmQrSmsvVzgKLS0tIEU4NFRWOUh0cXU1NldtU2EwZ2FM
            dVVpN0w1TUFhdDJVOTF0R09rZ0hsSzAKFYsjK3UwBr4ibajPLbjz91CPTVgYKOX7
            dft/z22HA7+X3xehTwehIU/aYzBewcL3pzajjW7HNRxsDGt10+GLKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:01:14Z"
    mac: ENC[AES256_GCM,data:hU0KjvRrKxEELqT8Wwxzg21q8oSWeSesa/uO2In4Jz5NF+Gx86TgrCN1DKWZyIaLYvytFr3UnhvdujNR2lNaJankrkoaUG1njJo0KWLM5zITIEPRfoEInGL5DTXOlNqmSoQ3H32YgeXKJ2m8Ui2brYz+CoZwGWwJn+CY+k8h/JU=,iv:cd9CrdoT7MdqHYq8xG9BITpvqwWRopsks7QEQHKKqFI=,tag:U75wLfXrzPcecLisHfgfYA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
