apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TQiBn1ngYkTEsrS+gksPwdrPQiTQqXnU8uEuohVkO0VFo0QqswDHiTrAl7QTyjhmEck8qGE6Y2ekVvZHq9Iv1MNlLNGjrpBHs1OFjyus6MwVIqXJ7YZBkQcLxTlmUlb904+KULCw6JCkC58tcIpPbHtS6GnlujIajID14rbI3fZw216SBuciEHXyl1wGi0r8hOPKcAOOz+qmPlrx9peuhPUDeuk9vwCKaMREBxXVWmRK78kESZ4Qb1tCUsUyFNh4xjSI4h29mV9KF4zRXTQ7SY9ZiuNa2QNWKg0PvZ3KLsMFtd5a1lkHvqg1CPi0KigUM/6B4KWcoKkFsTC8wPexI//KFZ8rApxvh2IpsziDF/Bbbw8s2+0Ny2QBLDK1k0Tk,iv:d5z49jmqQkn1wEwtrxhB6QA2HmFYa9gqKT3Ni5dtgUg=,tag:MMbyOF8QiuTvcsk4sqY+6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Du7sw633be6huzB7Kg/6ckKnaYRMYmnZ6QcvQsUpAKJI9tK2nSfoiBO6n9df00YW4jTZCMOgIp0yuMJsbhxXg2RDVNnLSbHmuGz0aKNCqeW41yiJdhaDKifvbvqcYA0lmWRbix+qVYntxp8iWKBTkirkXn9Gve4JQvu2PVcWbXX/2ZYdwFMZk/AgWngLHDKcx0DKkDFtb6zhVgxPYYZsKKGureRJKJ+pZddYB5lRdscfQgwKqMtqtmOFupZWV+iQpf1X6cNN6wHJGaDpRg==,iv:LJKAI93m0cyE1Hud6oVR2WMphVftePJRMMZb/vT8WAI=,tag:qgBywPfV4GuZIqnPl2IwiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wxO9/8K25C3rUM4d5BiWMar8c4paE7Po648r/D4AyNecLRmfHY5Qwh6pMJaJb+5BzCtr6zC2PWFuv9feEHz70/obDB0REsui7m3Bk9Ueg4Ho5TDpw+J0QhI0KgdDRaM5QG6wEDIr4VY5zYZx8XRZalEz7XdS3GijYIjGA34H5QSaW0PaN5nNY+YFSr5eZDqAqpt43xLN4f4rY9dwKAR7pMYZDL2pilN/ORM5,iv:0iVUUiLAgHTZ34KYmuV6aRoIlNs+6jufnfEI4ld8cgQ=,tag:mHMGLZsl53JC8XT0k5BLPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSzZhVmxzaU90U081WW1u
            a1RGWTgvK2V6QlBobysrWk1XTUVxbmNnTWw4CkpMdmt0NUt4ZXcybjA2alhZY3d4
            eCtMWjlqWEJrd3RJajRaZ1dSYkhVNlkKLS0tIDFMZnppb3l6VDkyU1R0V1lXdkVz
            Z0tTckhsT1RkTVFIajZtSjRsUXdUb00KcJ7CYSsM/XyP8FLCF7vd1zzel6gHBJSs
            xGv8pvXiho7XA/SI3+SzJk2oERzyVfWa8Tyvj/Ptm2tpJp8+V5Nwjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-27T12:37:00Z"
    mac: ENC[AES256_GCM,data:IWcgwQGAl3717XRlV0frRyTH09goM9b/0rZqH50mj3j0Hkl/J7WgFh/IvJzZELELL22o/1fJ1Ao+0Mv3DsVNF2m2k6i32hgao6FPE0MYvxQ9RRPaT/SY1eUVP/+y6a64lNJon5e8wh9f6sdfTEI2/MAMvSn13DjrxlVpSrWC32U=,iv:d/3Y1+7biOudOABWJNgefMifyBH3dgdBO6tTAltAq4s=,tag:yOR0AQyK95NwpdE6nbpv2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
