apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w1K4J2+GAIS2e3CRsyLZmHVlS8ySAShCWmRoGoJXwLzedqvMIOooOeRWO5Yxj0mSpiejSVecjqB9SaGpLve7ZQ8FIHtXmSjuT7Ps37f3kHMSRTF0CSn6W0c1wTv1cMYPT52j6EHbwJTwJB0dqtEGZEJAUu3C785g43oEi75vP6NVwSwHWN+HsunxaQjKP+O6JZ7gXyc4TXuTUrSVpIkC720eVQULUJGsD8SPXx9zjSo6jsaxCJWjGY+eETPjl2tMikDceP5jK3ZbcjfaUDbJZ926Y6DVYLNxmBOjxTUIgGzeDrXTR/NisZH8S5Gzd49FOr6lkvCyGZ8dApYC1IBqtpItdJDOnGTvQoAlWExS9IE/yuCUja1EPqlwoCEmApw7,iv:eP05hIFg9qmrfGo+azWKpWQURd1iW5JaIrp/BsBNhJU=,tag:BjjBblV6CVvstGcJpH/BYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:YFoKsHtNfiumZyWBakZfLSQCDEoy71ORlMHWAXaWbf9mHZ+KCsIuInkv+KW+TQi5k3YxuwN7cVbOz/riuEoFOJJOMhBSIJeHAzEtOLw+8wkRCqBYZl3zECA+RnggypUKe1LD130UV61wPQU8ZS7xzkoG2LZqZ60qkNCx3ZtsdHw/RYXxutse2TPxxqIoB9V6ppX/no5irhy4e9dJmQgd5nk5Q/oRP/zE9z1fpQmJ8mFtzBgrZE+NEjXelhCadCYNyWXuKws2uMTSlBYXwA==,iv:TYdHOpul2A+JknGQhremrNgqQBpMyHknu3f/uwmZK3U=,tag:CdiT25xvaH5E93vU2omH7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:hd+KsOjxqWecXfrChwDtwM87TAJbKPua5WXD66a52z7LLLAVHwig5p6c2FQpR+IOvU31Gue+t21DcfOnhYVF7MLYT9xQdEtE1sHl/J+nJvd5iz8kD3jyGR7jEfBwZLgb/S3v+OiDw8htqSsOvKTeQ0TrIpbgidonRjGdEe5Fg+gaLGGgAAeHoH7PfJOr3lsaS+e9Pe2vir3CnLraw1PxMbjuREzu2p4zL2Bc,iv:v3cjh+e5c0sgVI0dTzdlwTNeJtgxJtgP48MscUGfWPI=,tag:Xi1c7Q9sFbOvgZSMmTyNJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMzRseVA0QkZzRUFhMjQw
            QjZqU2E1S3RTZkZKUWx3NGhOaGsvYmhuSFcwCld4SWNGSklIS0grWUozWTlaZkds
            T20wNnJhL0pyZzJJbEZsQ2hNSi83R0EKLS0tIHMvTUtTSGlxSmpreFBWTnA5ZmVn
            c3RrV3ZGNDJsZWZEQjNaRmdueUpjUTQKWlXwigsOUcRwdry4SRyQTBxl4EKUp5is
            B/140rOX3Tg5aFcewlgkU4aIVazoq6G31WOxepqm/0Q5BJjr8zqbpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:13:30Z"
    mac: ENC[AES256_GCM,data:3EZIuo5JRm2hIwb/+eL1/VdffsFnv3RSyxDfGfK+wwr5eLjza/8P0itio08A063IXFvljlgBaAqWM2xhQL1xY5XPICa4I+QDFUX6cPqU6FQVPbgmzaKZoTxQQFCRLl1oMMIsTIg4ynBijmFvRigwM07kXK3iQpBEGejb6X9zBBk=,iv:kB/vtDMqcW1f15atfzUZJZfXChsD7iyPAVsj1FagVYc=,tag:ypzeUZjI0rynbtjqwQr/Pg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
