apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oBRdmgdFSRBYXKIoVuiY6UkBeVjyMmmzgXYdTgh6svMdFuI2RuT//tr8Wx+jTDO7V5d7EGWHMxsp+ix19UO3+Gm1qWX9iUJOKWiiEUQix08+tg1YPhIkSJBXhP9pfIXGHgYyX8FYoGZ3Zx+xFyYlJ52aMUgY0Q6Ei/yacqCKSoVTIpjLYMuv4gLQdzhBBVcl3T1Z3u651ernrsDK7mWDCqmRNUpXahGVGVyjOzcuO0CcHyu5jJrpUShpw5o0f4TCOjq5CcUl8VhNLma61N6VP7etpDHwSvxBr2Ryokglk9iJXt95a+t8APrwXeupGRxyhyoa0yWh1wcdLjM1cgHBYAkx9ydKBa4RZQ9SXzOp+vmURiN1FWdY6A0Y8gPv+i+E,iv:dE5+EfrnHfRT8dVUSiYznEYWE3LUEE6s7BjHbQPfbHY=,tag:4Zvoe2kHg88w9qoxffAvtA==,type:str]
    identity.pub: ENC[AES256_GCM,data:RG/6Nrc2sj+nLktJ6cYhRpJGJE+0wijAE6DWlIYUlbzjB24XaDv84WnfabwcYL+oADITBaozTXQ+fEI9nuysaEcuYO7PykxNxMD0zBqXsl/jWNW0EbIbkkJ/+eHsxKSN/XCt8gCzJoeJHgo4i8xLiWkAG6FBm7JFAKg6mdX+MTJMOIfMqdkK3NQSTYO+97HI2kchm74uv0LvHyWeBw+aW6QKI8XYaFzaK/Qc0FtWQH+Y2+i6AkcTSgsV4Gm3x3MoN+fWwoy2f4cOdsvJRg==,iv:K4G5xOY9r/V7rlOCDGyzbrEV9J9tcj4haFNmeb8tcF4=,tag:MLJZXYryaJx/N/F25UMh/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:EEb8tLITBSWCzK9qrnHVmS3rgEwFYEdYwCr/I5gFk5zd6gF3tCyymUtJgNxGyEognsdQVIvt/AdJKZ7dJJTUd550Qj2GeTYNxlszyy875LATJUEr/LwVGHxdfZaZNUQMcLxtQ0xLh3QTmacQQuwc1G+rMKlvohXdgfRKw9gW1POHDxExj5OcxZhpS5t0X5A/kOqR0d5zC6g5N2iACKNVTyrd6Tj3Bgy5UGrr,iv:T8IrAcv1tX2X0PDH1LrxjIO5HH10uusHE9fIe4yzid4=,tag:B1mPpaPM3G/NwRFPOvweDw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMWxMdFZrT2FrR0c5aTVt
            MFFReTFYbVAzb2xPTVc5djJWRCszL21ZOUdrCmtBMkZKV3lSWndLb050SThGMndO
            MVQwM1FsRFl6VUozUTAxclBVVWVuVU0KLS0tIG1yN3ZRaGQ3WUcybUU3SDBzU3Rx
            a2tQbkNFblVVSW1HVVBHN05FdHRWUk0Kqq2dDr29wWrnzJzCBgn7780IC1WE+1hS
            2b2A0Z2umYtHu2GVE+F1O923JYIvZsjBjsKxqWSUNhHGgrZl72/U5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:31:24Z"
    mac: ENC[AES256_GCM,data:WLPpdwoDX21YYu2kFbs1knCp/UiAHGcNSMvkjtpcGBxvuyJFeIagr1Cf2vXfL7IDsfJxwFoSe/efNqeOy70Krh7XhbUmq/J6F40SBILMCxuMqEXER6L4e3lhI74KKSivoZ57gX+2OBas8e5RkbBOSpdrARnsdCQDyxtVZHdUnqo=,iv:XE5Pe/T4EofJtohrJQPkaJxjwhg20oA8h1+ihi3JdOw=,tag:VAFdIuHp9kunkEKg787OCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
