apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Yp1SgmSSXwbwx/cXCSGOKOa8yRu3mfsJh6PjHFosF2JD3XmJIFWkTMaE1GRI3Tp2hKrIi4MGHkvxeWnaJEV/jvjt4HmDdyllhU94nEkxd72Y+kQAo2egz46fL1KfROZhOAaJRYRrhh6n6ajhhn/5suztDXVUKD2DDhR7bLpOLQe8IykqkbMeCiFA3b4a6QLAbSMI8FfHKmaAydz3Nb2uXd4F2EEv/CYLO04VeRByq65lHGouzFpthMyYbz5kCVZU3RminF+ifX5zalaIBiRYbgmsGrxZButvvzQtE+GYlvXNdjBBF32BrTTM0fee2SybBSuPHsKBZNoyZMocuioa8DCTpuNLcpZMCqnCq2FlR3CupRoyD9uBaSqIyHXCqU1b,iv:XAZHOFM2L8ZvLj5WLKIntHsAbE6ba4Cot7tx7+aOn3o=,tag:MOITI0JjCWArPXc7ya3L5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:yg0JjzGuyzPtU4ZbpwrIJbJ5HEPz1/D9p4fwRYkD20DZroYjLnyN59o06/3iar1ny2IX7HH88mOaRQAKjCv/Q/dkr/t3hkr5VrPdT1lwBIwkd4VQFgct7GDGA4EtmiGF9Nlzmof/RzSzSGRZBGIXH44oZGxHdzNMQ2h0t4AdSAyOazrP2bfaJ2Jgf9f3PgU5AObfBiH7NNuZiItejql2ORfbshx45W/QZuA4KxxIQvoIIdf8FmieRQK0GyzIwa82C7+Eg+CmtWybapdUSA==,iv:HNtUHvZi3yq3sAF0kBeNb2Cn8+T+ov1jttN3hWlfwAg=,tag:s5v6QDp9SsesUuaULSXmIA==,type:str]
    known_hosts: ENC[AES256_GCM,data:gSI73TIC3P4JJIlNFE+b/49Ur6MNLjE6ZG/zsehMKCL8dM81GiCUlaFwmyC4+0KR1WEK5P6QfpoDC5rrKN7Rf1Su6tmAXqnuXJBGaoHNk9bm+xBMnMiygEPBvQbUPhFAm3oaXX68YEr9oUv9lD4iaSv+dQXcaBwVUTEOl/SO8EaXZWVGT27wev7FmtmRAxMaHNzwG1Cc7iQiPomC5ehAo+A6wfiH6nXEVz+W,iv:5oHEMvL2Q4GrBXq7LCTEdpO9TOjcbgxlqskf6Aa/KxU=,tag:Q3KiX0ParFpRJVFGMf2upQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRGJqbzYvK0QvbFFwalY2
            MWRjbGN5WU9TZDRwNXpGYkdhcGczTm02b2dZCnNXRDJoZXg4QnlneHVLZlVFZ09F
            L2FjMTNpV1BmYnBTYTJIeHJBSnlpOTgKLS0tIDFrSTlqV3NDL0Evd3VtQnVBSzZn
            aHJRQ0d3QTdBWnJIbzByTmlEV3pjT1EK9scBO9kRcg7GdyF0KCvg7WpTq/wiQk09
            xPti/eonUD/JPwyoJ1CYgES1b6TPGQy7dGIi/7GhEOnVQDz9tw/LLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T14:39:38Z"
    mac: ENC[AES256_GCM,data:48vJMg4WJXbGwR+5HsKWYeuhIo8Jpx+ebPJ5OJxr4q0zAMXiDntDVNuyZCMHlwC8rYc0rd8cyroyGYmC/rjgllVwVDUT0i8HWI2DbIW03f+QkcGzmLl3RF59emF+KG3pgBz6yOvwSIcbC53KswGCYQXJJOWD9XzEwGCcmF5Srqc=,iv:yTLZtenXR8p3aCptfsDyfYpCmOHQcGvOkE84hlO20Bs=,tag:8a7kv1BEHeaJPpVROG1doA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
