apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JEa+/i4LYoRDIsoVT5c31P71Tx4lq5UST5z3ff/ukcGoqqG+CFcm0zho+7LQ6mF27vH4zdx1k1kFnZHRu7XLcBQxUQ3CsC1915UbxGt9TnFc/Fbtu9rKUYoRp1SrgaK+SVn295pAsnchliXKRk4XdHy752ibrXrGDKvo2KgpLK6+kEX/UBwlDyC/vZSCdWsB4ORVr9VJK5DeJmJwHkn1w50YNUm/EnoAHyAPu+pdLYQK2OU0DTLMYa45+wzVf7E/PcMz9yiCyy7gIoqPu+n/g+DPCkMnHMNebq2MuMyL2tahZH52HKL6Qyljb+VfhqfIXlCw92JCXHWGyRrrrcTnN8mh5ZP8dxxRuKTL235bGCJex3RV1I5LUrKOWB7wEVsr,iv:drUmfzonKJZVG9nc6Hz5dkH7UgPilt+/rxWLEyzCBiQ=,tag:jYj9hD2EB9r54sSkhwjeBA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ErS8iZ1XhLoKIWA7VBfJ8j0zbzQSyy8M+tjl4x96lsZK476hbIVOSbkcj8Pxp3iI0eE3C7ordkYR9JJ0KZ7yiwyD/+YWH1EIzGmfxmCnwjvkR4V5F8YeIpWSFknplWvuvysjEpMvqH+uRA11T1aQ2AltPyS4KDiZFTxrFV3CfylPf7DHz5Az2r4pdTdzPAuQrgI87HVWW+cd1eskpl1Soi5Vs4fPzlWAHKjIhcmrcDHCVltkkUoOUMcaAv810HmxdORmgxvDCaxDWTJPkA==,iv:2sq8iYSgo7eeyhtRdzDb4HpEVngw07rAYwjQQ1FJZLc=,tag:27uhh/SUYn9H6W4sEUvvfw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+mUz8xQVKKLOY/eq/WZ25UM8XOkgweSGD9QVc7dxOBhNeZASuPv0lNsjoMVn50vE24jS4kAt/RcNi5ktbUhRMJTCK5MQD0a8WmucX68hKD1L8Zf8oRmQd+yvkvFVJBg4JJUO2IgyE9nAqm5/a2mWqgZhE/ezvIUJBTGOeT6URNHGVt2v2C/9JynYBwNCbgi07yvPiaDDCVCFZlkr1rl1JUPFa976k6y1du3U,iv:jSd4LRUSkP/fMeYbCz2Zn3fgm+lTfov1HHFy4wuV2Q0=,tag:jdWEqTVTodgqqX12aWYAAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMHFqVXl6c3Job1gvYlFD
            b3A1eVd0emY0KzN5M2x3WVhtZ2xqaUNWQTIwCjFUalFhMFlrQ2ZjWHNnWWFJOWNw
            cGhMMkNCaWE2OW4vdC93VnptYy9BM1kKLS0tIFRPSFFFRVVSVnkvK0xVeGRENjMw
            VDNHdzNJczBtUU53cTNVSk55TVNRTmMKelDZb8ZWlQg2Kq7i+qZJHeRBdHzj+3Ul
            lhlSaD1ThQMybCsB8g4yebQyqNAlK+cbgE9zjsRCQn3vXpjOFbG7Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:29:49Z"
    mac: ENC[AES256_GCM,data:4epr6jXpHJGTyovbQSPbwXmAUSvpjxKVwaBKZabbE09UwVjEewSrxeD/3Lwqm4aWFCYqSshn2Gh3AYV/Hg9sXcNvZfqCdpEPBYVHEX5jiyIRqs7MKqYrOUtqPDwoBz13XrmPI/EgABdwI4lWvrh1cZuNyRyiuD50TfXG79Y3Co4=,iv:cSZEeACu27uAAuv4oOGq5rEObSjPez0vyHmfZdmDURo=,tag:w51orcEUxNSNvhBtYvgkIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
