apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:C6awsLeixQFsoxPUHmGjQ+C65aOlP5aFtWUL96ePhpZkK0dsYJ8cg6tDtXH7Rl4bzO9lnsf9+/jLQybxFJOJmTHWg9s/Nbb3cllqZrp1hw7VHeihR7L7+lneBZAWpwnSciLbVWB814b1TaY+miqsqUgLNLr/orqOg5yprpOvBERqJfLfUNqGJrXDfehhw45M+m1CihtyY7wvKLOWhuEizLNEd5SLMoOqsUZuss6v/T7DHIEcX5uoKSc7dHSBwXkiVEN9eO4JE394Ei8LmpqgkwJ8renNv0H1usdVoTbah1V9ciOPnQfl2u6eUGGH4cdALbh3FNZRCA8aTewNUQmUuC6OjFbvI+hNgv1/zvGmD/L300IFfhstdltc5nSIuVFT,iv:VWooctQ7kwHKMHyRpLIq7P8XiENnEn25hxlOCivbDl8=,tag:GxAjXabg+mvG4g4ByQS+pg==,type:str]
    identity.pub: ENC[AES256_GCM,data:bucKV9e7vQE+EcoPipBAKAOLsXcVAwr5D0SAK6/+PcgbIV3by8C1pT0sTid5ZlqAkfYFYpcgeGCUbwdhr7HJuHn8tJ4J+SyqrwSfDUFO0WXBAZ0xN0GnG9+VZJ4YheY5npRf9wQOEpZVBVgwhn8yVk8sGg3SH9QPG5SKUGXba9U2yIIGezqNLIW1We7qLZdWV60pc6cvxfUNRCgb7h0hgalOFprXouRXvZspR6L442cumYVogEvUEFxnuXCw6/kuGKM7h+4e33fL5mC3JA==,iv:Jk5KXWZ6m5MjpyuBNgObyaM9CFNlZnefEpPdcraeLZY=,tag:OZBfpSN0l7IFpPxEsvkTdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:aEaLpGAtuLs+UF2d7c6CyF6AAb0yLB1wJgvi6GSvfssQ3z/zqisgsaw2/sK/JwQiLE4XQ8krduFjuvheSQ/PKKeZV6scXAJ4qvEI+sUIwZTkRYoMKTqye9b/ndk0FdMksgWioh71S2iHUTrB6ZagEfBH/6HGoIysnB4XtrLELWLBxoraTIgM+1IT8jYpDPVFYtmljvK7lZDRdd9HPWw1CT34tHIqkal2B/Mx,iv:thkDHgx06MbWugGQtNkHObEltX3t2nv9K9xkaitEbeg=,tag:JSpebaD+Q615xCSe36o8/w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRUJucHJLRlpYbnhPc0lW
            d1AvbjREakppQlBHaE1GajZXSXA3Q2l5SVdVCjZsMmlZSVRPYXZXcmlQZk9sRFBT
            allJNG5icUxnY2FFa3dMVC9kV3JteEkKLS0tIEtsVFplSVpVcmoxeDNKNUVGZVF1
            U0R2ZytWUjJLL01VY1NYOCsxYVVrTFUKR5YitZmeaUqyKPNfEMiy3Y6EuDGddY2V
            J/+c6fiNcpbUa5jDA647KIUtQK/vORiWeKEaskIG/XZXI7EJ0vhoNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T01:40:05Z"
    mac: ENC[AES256_GCM,data:qZHv0VY9NnifUO+xgK7v1HoUroZrXAmlLzG7typBDFCpyemS8xtwrkHtLRBEmi8OBN1vSSf8qMAuMAr53DuRRu3dchPkGbg19xGOq+L1hW6TxCTn4BzMxdU9nGpKLhOBVP146tsaY0+1hBUJOeMwjhhPYNvmeTOW23rga8GEW5k=,iv:iczM2p0GIra6CRWhEeUuv7jTyQlIuItFvuntttN8H0E=,tag:VgWKQKyPprVCHV12pZPLsA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
