apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UmV5/IgCzJY/gY6Pwrd2+z1hk5dg0Roq76yHM5EuprJjqxV2aA7OyizAFUisbR3GS9o2lLpPDc4Xhng+2YNFQzeNRFAhcztaYg6wrePZUOWFkDKVbAzzAPRVgOObF1lEfo+Xq5Vfa99a1nI64SOzk/7T6oRYTnnqmIbj69SyV0zUv8isTtDRoN8Qvu8PvYf+y8DQpPMCATtxvQ0BXXNqH4WHlNgfVdiYNxPppSapTcqfhzmVEiQGiP/RRbWLtB0sVgY2eBsdi8ShhaVWPArdAoieDe0LRW+N4mF5wunY9GahAow2ohlDw0xoKtBs+32xVIzwjD5hyP46zLLxs4GDosoRpFB1LUf1yoZQVLb3pX0LBmkhYd+dlzgR0uDikJeO,iv:70jxEnjoG3CSGdI778HnR8jwrmRSOFPfy0IAUr66+5E=,tag:W82Slx0cYEYurYwX6bV67A==,type:str]
    identity.pub: ENC[AES256_GCM,data:wiiLSvbaxAzeukzr311iUuFkJuHIZFxGwTcsBnrAk313EO2DM+l1dyTUrWTEduczElrHix0+D6rLo+l10NjPS9lrTm6HVcAaJ72NtCP8CXi7y5bgyT8nYWfitdvkqUr6zQxcW5fGEe7XJ/xwx8BhLPCp8VXgWmB10pIAmKNMe7Oi4mqqfRVm1Qyw4LCTwrVhqugy3GTem686kpFYinq3g6UGak+D9JiyEVflMjGRrb1zi5Yku59xKN/dlPxFqE3YVxVJ0dNtz8sq2zQw8g==,iv:su+sQCb9IkUJGqawuhSg6Ayy5KqGtvOIVZlEXnNNqt8=,tag:jpJ6AoaypGeUAEolTVvfqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nw/xhcJHwEpoHrsisnoMMT6VaZsiuAyBqOAQW7/woM0GOloNKZsbOW2MENy+AnR6luZ/Nh+/QQ2ifsCvOheuDEqpPAozTtbk2rS4lZ1ku7nH7isYNjfJKw7ak/zaJGqm2FOX9smfoMRSyf7b40g9FKd+vwXqH9OfoFLdEqWXc9Wdp/p/nMCPTS5GZBhE11rKfsKUBhkhCXLZAS3iiPY3FuvNwLMV1Zi7mLiF,iv:RyMxsEUrt4oj906Ag+YK+xWv6Jj0nypEcDuOwbTy/GE=,tag:h5jYGojqzY+acDmMgjcvqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlhMOWUxU1FwOXJYbVFV
            bExnUkMyZHNuSW5pRHRLeEpxdUtCK01qQkZJCjlxUVFkZzQyR2VkbzBVSUtaYnR3
            Wk1vMEJWTGJmcnNXTkxFS0diK09UL00KLS0tIG9ZcFVFMnJMQmh3TERwWEd0ZFVG
            NHhKZDRPMnMyU01IYW45SHBxMTNJYWMKAE2dHxrdzGvsERGPG0gNRk5DAuVYF8DK
            2Iv0aqctvIe7dwTwBc3NURFKe2nC2jWf0NFo5tzxFarses5GtCmUrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:36:49Z"
    mac: ENC[AES256_GCM,data:CQYXxN5/TijytwfKcnxHOo+kijwdnaq+tERPR51SCpWAiaR/LOrnvwTW9Y9+frmmHhFsVwDRNiR3lyZw9fnVYjIDpD5GlekjZnb4hHqPJQMRvVoj5Qj0z3joluIxhqzgXPBNRfSDatSQnmjEoaXl/omOx48S2LJRfoXzZG8k6KQ=,iv:7DJ/9DqJ95gH4DMfIGcNw+AmFMBn+4+A9vXE1R57e08=,tag:L9XsBIw+d7W9Bhs7EifwRw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
