apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kx+sO6wcXJ7fEMZk3I+rzfAIBOmFC1ywY3bdw553yP9g88u6fbYyIHpAPVMzVd2SIZb9poL2DxhdGSLDc8g77REnzcrsxhorSbonnjOrn6wJMrWcMJfpfPNq8vBXeJYHfKZPl3K8Tcg0RfwApUrUsLkdxuzzRPQ83JKsj8FgAmD1f7rKN2+q+6fVpNHTZjBTtcB08gt8agRIatqLav43q4LFUVWi7/4yU2/zhvT9Zi/LaJ1nzu1GdqYUEtBpKhOr4Zon+klHTBXREoaa1i+tEhZwD8yXM/maivNSiFzQwSSSN+kEt1Utn6bct/fkKKgIJaA8ornQTSeQftCXywY5mVPIa42Pxmokv34us5Dg2Q4P0lFvHlHjEIiPlh8jlyDB,iv:IZM9vI2xp6BC8g4Z3pD/pwbJAyR2q+44+u2pg2o+d3Y=,tag:VRS5VfxyrW8qt7NIbN/y8A==,type:str]
    identity.pub: ENC[AES256_GCM,data:jT0tuvBQotI37pdA0HvETDvQ/txQATWkaV76j14WXjrKWBwLS1ou0ugAt4IhJTjlcvgbhxRe376B2XXg7ga8OYcPUI/N1bzHVKrAj1TtHMuTf5dXaaJN5KrDa5z5tekOkxyIbFx9g1a2GuDO7lseh0+Zr1hoGMPgWuVzMR2jzCPOnPJwYVtqAds0CIHz1gwdzdrBRbPYLT1QKJiinj8d9Jlzzz536/Xfgmg9SP3AT5HW2CSd/xKwlAz0wbCrhQVsJtJ3tsTMQIMa8X7xhw==,iv:3Q4QQQYysf3Z2Zem7OIGDMKz0lWEPy4hhAIrLTzM6Gk=,tag:0L7r9FvtYDdM34ukMSJfKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:u63opzeIkA6U26fAUijHdyt+ZuRg7XlbRITccUtQbJ/EVxSDLefbS653mnAb0PjHmN80cQhNzA2ua/zqAZnI+MQzBwoXS/o9JWjUR/4hpz6M8vGWCZHh6dY6tcgNIeGViY47fT/b01M8SMl9dKazUroGwE0yEd9A0D1jg6m2K8DQK5n7ytNEqV19/siMOFOgsgwpZCGxSzJxRay4VevXfh6aoB+T5jgFt7vp,iv:SLEb/itEZrXipATeZOHQ8rmP/8+TK8zv/uw0+mWsKbA=,tag:ZEkQAawG/0rLC1cvkp7I7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YTRNeTEzUGROdFZML2VJ
            RkRmZ29uWUNveWJlZVhSejdtcE84MDlZL3owCm1xTHRsVXBJZnRLZnpHdEZVOSsy
            Z3VWQUNkbkNNR25aVHdheXJCYlR2RmsKLS0tIDJnU1cxdkRLbkFGcGlSRzBmc1lG
            ZWhVYkJlZHdQOUdZQVFPTWhTQXY5cVUKooj8rRuxiO94p0WuVhgzOPBpBLRCgFQ4
            d/KW0A73AcLbEjF+P9w4zowfHENkKnlTLr0TtRAM7ojRPm4PaOa0jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-27T01:25:19Z"
    mac: ENC[AES256_GCM,data:uAJ7StRzXO0CZJifaYtJij4p6QiySHBeM24tZZZlM/9rtRr2dnJ8Nw7pZ31K8pPpLuB1LstWnAYqU7t1v/RpxIqVdz0Zaonu0vEJIUvfuxM/AkevNl+rqAIG9i8UJXsf5NDmdG9Lf9e/MmDp+OfwIHD0cZNHlb0V2nPoEyNhEb0=,iv:f6tRrUN+6kYyBQZKJsWBM5lQ17Fa+GUP4KhG5OUbrcg=,tag:juzP/rd+qmE9KMtjIibnog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
