apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TINqEL2AcC7WtRRtNREw+XN0Syi1x+ulK0NNalcccGKyAYpC965Y2rn9TG6qEnbUvQNMFHvC6sF4grwBysi9aBmZxCvB9vgySi/LaceDwqkLxR6VtVikwmPvgapY2Atbgmb54+vYVFdrXRUMvQwveAi200LshsCUIS9GQBc/fu2h138T8Wlg44CsfuLoZFeD9eVByHpgalCDh0kS5h3ifVOwmdj5OpKzpan+Lq8XscGyeT02TpV18VuJ7/oRx9JoEZXQexK2UcvMG0xr3N4KBKa+Wp0cDaurrn/fvYGUYl4EMIkNOChxwwvNhZuf94MgCB58Zw/g0cijQRDbLNBJjWCd+EbXzifBsiNoSkjIBlsTG4VE7ZuC5I1i8gLCClV9,iv:cBvbdXUwlierG5fjDASBAsdlwRfQQjg2Mw/NvqXStGE=,tag:w0wsHMo5Z09FJutSjHuorg==,type:str]
    identity.pub: ENC[AES256_GCM,data:izVi5uj2xi1dJKPnYpJfvJ6adDe8OegE34HpXr4Ez5PUF4xNwuRbEzXR21pwXLp1soaVUx9qanxrGPspkmnt/mpd4BQn5nAO4nciEbjh1XuGnbFmalyUo0uoSMe84xf2aiy7HRObMU9aslmCY7fLKZdKitlv917ddVuue5Hq8htFiFjFFFZF6r5BU9UQ+J8PO5Z2n0LUefu/f/bkrn0Hzj2sAk8EAnWuaC9OxmB/wzYwgISSrt32kjRf8lZIR+bUN8M+2FX07klo35Dbdw==,iv:iNfECY1iQwyCw+VSB7Eb05L/G5auDcVVGaNA9/ULFms=,tag:4N2WN+XwoSF+nko5ofrHhg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZRLj6l7cjBG9h90ye+EL5zqtqpHubeBLW82J3EMRfdZgjJ3MZdH9Gzqudr2VQQOZ7D+pTe/XQtFyocBCwa4RgR1vbaGsoi3Q+y0vChALLVXMJlWCvC0y1sFBnJdf5vrhYeKSbvTcc0nadP385IwNS8RWFFhBhIGpUcQFQB5R1m9JEHlnxdrVSe47wfV6qa8OsPwD9WPvt+CukzPU3kIdkss0O1B+5Rfco7m3,iv:sXtKSHdzbynKI1ZQljmXr3iEgmAcDHsxukzJluf5VJg=,tag:kieZHOa4gstiphUcluYtiA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdDNHN0xXVC83cUhHTmhu
            WFlZRTVEUnE5OEVmRUpSQmVjRmR0NkIrYXkwCkFscGJtTWFjS2h3YzdxRkJKOGhl
            RlNMdmNjWEtkQXkxTERDMnZXTWQ1SkkKLS0tIExtZVBZWDJLZDNWVTNFU2lKemF6
            RVVCVFBNaE96MnU1YlZVQWlDRENXV2cKwar28GN+uz8ibG8hNRJqB9H41N/YhuX/
            Jfe1P+D6SYd55/QFQvLmxtH2/uSDMj1w3dI3jHdILnHN5Fw6mozQIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:09:24Z"
    mac: ENC[AES256_GCM,data:08bL3W9DWNfBadCJbxXWoo+eXyGgbO1MdAEjXZtRK2iDV6bRo5VmZkfGmtIJtSCLjpTZH1wpEy9sV0WFeEWTQI3REbHW1NqBD6LCgnr7xHg6dJg/ZK9aRHUfwXa119t2WAAUkD2NKTX/fovidE4EdjO6hm7Hv2UQMivchG9g2Bc=,iv:OpPS6FHiS6Q45eQi4Am/KkEsrI1w9txrDa0/PxYzDuk=,tag:8A6stv9X4j57G14BTcpOuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
