apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iLV06k5JoFFE0Oqk0YVOMK/MFt4p0P309RxsjSneXmCWZoaEKl9k9blGaaqREOTU7sxFVUSZlBFXxfAemKAGdfBBA+LMxy3EhXP87yCvnDsjy9mT0kiK81P/GOmq9NnRyPse6Jfd2t79dgMnttSGSIVA6mXLsIJsTtLPODJY3kbmpgBXxlUikHHIs10BcD8YaOspJbWXl2NefRnpOMpkdKkz8dXIGBN4EdDSNumpaunEA3ev7h2fk/jw4xJ71SqV8kXC2etXYPWUM9jF4iSmHdkKRO1HBxiYCDBNTWHncmArxWkI7mMsLNxQQsHJIeLtoaxnCIaVn13mPa7hUuX01HpuHC0fK7IRoBz+F+eUXvrpMJx5XAoRDl77Zf4uJ18+,iv:8jhe82W7PWRgAiJwONVQ2GNokngaWu8WMLKhJ4SjRZs=,tag:Gz2Co1zeR/MD4+fROdN5UA==,type:str]
    identity.pub: ENC[AES256_GCM,data:OtRqMZ39gyS/aru3TRIC/mFOY/m85+e+yWltEPiusaHPJmw2IicCjRYIGI9WqceTifJTK/TvZkm4tNp0LdoWtyOWEpKGD6sq7Fc1IOdKIGvVycTnIasA9UwlcVYE6xeNxumrzJUa9Gl0hB2frk4S3VnP3QmUi2oy0gXXwV6LhI65zRAoMateHBLHVIG90Jnc4TdCQgC+4Jha6GTBdUF9PLTNbPSuDcdL6QYEorZIQYkXM+N30n47dAmuEZWYECOYtmivIiDnojxOgDwJxg==,iv:K+xSKpQhTamC6rfbXoKae1jiixQXS0ZARveSvblqCdw=,tag:wSbl6+9dHS6p3IPQCvQDnw==,type:str]
    known_hosts: ENC[AES256_GCM,data:AyjTtVmLpuSLgC5H+aQ5MsUJ4hSxEi9OVQXXxB1nkaGmgukvkgWytaODIBRV7ZGGUsI7xeUmVuGeQGITjpZqr/G7KlkytYSUC/hWfjPU03IgoxJqvfbsBRaG6h51Iayo9x/eBD4Yr4v4mIIGbvByxt2pTBFhkkUPFWo0UPHvypSdP+VBOLb05pSY2l/rJPVYgR9eTSOW9i9h5e7D5rNL0w46bezrSqtzQ8Kp,iv:7wsPm4HhC20Afsm5Orf+AcAwktb9oliV5TY6rUNN2R8=,tag:8wGghhRMJDquli+HJ+PG+Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UXRUWklJQjIvYTFsK3c4
            ZUtCUk5IWGhnelRyTnp6NDBVdlUyaUpMZEVJCmFhQnBWRUJNTzBQZUZkakx0T0cw
            NFphWVlsWGFhTitwdHdpTWNnQWNXNlkKLS0tIE1taS9mY0F3cjRiTVdQdlJGaThu
            TlR6MCs0VU53K3NyS0t1WlNwOXYvSlEKqxKAdN8vn5kX/TOGQdwPmqq2J+CcQo57
            6qEvAeAECU9yBZmyqdY2yNSnVoU02VN+vq1VB5ELOh7+HSecc96vVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T15:41:28Z"
    mac: ENC[AES256_GCM,data:ydvDJT+iVXshBsennZQvhg1/YOEQBGhK0yIC3J68LnsDz+VsI/cXJq1gJxz7XhbsaZ9AvYpp0N13O/4itdy9VgT9lEV8Tp8YGYufvmTJA1Ga7VsBCeNzmuuUku2c00YUv9b3tUBkofITjBtVv4/vMJA9EShvSPKS3bs5Uh+qAL4=,iv:UiAlixw0MBPKr5lXJw+1NrUnCKVUxFOQRom3Un29Vkk=,tag:1Ee3taEpd+PD5rS6lHWAZw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
