apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qslZbxMFvtlfpBQdjkoKd1c1I4xw0Ux4o4NJfDcCMlMjWiQl9vtMEXSd5JTVedApcUnR1ALb4ZZFXm0MH2YMUiEvfnNmxVJ5/OgpgVJleTAYxI9T7YiTVB4NwRRyvq52wCfABo2gMngDypGeyqqmL1rQS+/bpXsuZuFuyJfnK0YvLh/9dNHO5r26j6jpW5JFf5ubK7KpRtIBw1NHD1PZSjhU3kVeXYQH960TeB4W1Rcd7z07XgZafYKGJVkw1QvdLCyKNiUZghLOiGKxYjhFE/cNU5+5BfXYwySfrFEoMeGySWLDvax7TH1RPzEB7FEuD9KlGf+x0rsFG10I8IIH9I/WXfLvPj4ZqEUpCckxOb4mnCKaBaB5JWcZMUA98jxV,iv:3D9KacSxzyUY/BVPZc43qFVZpLZsFp1Oipl4c/CGqR0=,tag:nb2W3k1qJ6U803T3+j3f1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:8J53NNuJ4xl6QIGKnIkU1ZgJjZc0f2QoABPbIcJ39NG+ZF9n+KiuRFXSZjYD7BCqxnNRXrWZDsaDOtNMKY9z5l3+PC/0TfBEeMfulPhf4rnYqkcBWGWPGHqlMAR9mpeGnQpXH+tJ9rmMRXyvBg6VctZvlY1lWDfSi8d0645QDSgbflaLSMFF4hRmBjyOpEWI58I4A3w1PMqN3rhg7ucZgZkcKsL5aEEl3lEenyaHiCwgO+WKu2mMTlcIG2i9ME7pMG3Rer3cj72uyPNTMQ==,iv:6ArELb4GHjqkLluboGAE4TDDcxLIDag5lHgePwtbDGE=,tag:Qgtigrbu0sLYlq6saTmaqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:S8TUQ/KuFmsXl1z0indQYxE84/I5VK2VZCOj2hWFLwqaNN7lLcT/ooUACwMEznaJK/bDDW5ZGc1iqDohlaUiNz3KCW+1Ie3gcfOmR6EcpleseTgB4Ue4DvDJ91JEqcaU03Ozp+XOEd12ngFYFDmoDe2yzLx9rhKwbGWAsyWTBwISk91jelOIvsG5z7XNS5kY2hh4cRoJVLIxMUKTzXcXYtsdf8AOP8aAYasQ,iv:SQb1vkL0vhGh2KcsPiT+OimFG1l8WXLNR8OrFWJ7gS4=,tag:2HCOPm1ki9INRjv7+98lbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmcxWnpNemUrcFRRK1FL
            N1dnUWU1dVd1blV6NlZPMTBlN09zNm1WeW4wCjdTRDZGY01IN21URENNdU9iTWY2
            dTlLSkRpa2xnaVNRdGJvU2IrSHJUeE0KLS0tIGdwQlRVT3ZmS3FvTHhzYlAwbU9D
            cU9jdFp4amw0S2diVlBmSHA4b3djUmsKkeu2XzZpNkGpKOGEXwiEgA3p0qA2qAPV
            tXiHOKMxlOKvXDQmCbAs2C/ITkywC1fD+xDdQQ/SYItPUSa5I/4WDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T20:39:50Z"
    mac: ENC[AES256_GCM,data:tdbXhJAT3Blb1ozyKmK8B06CqpZxXsxh3X3ZfIRtfsZlUFaiQo3BnHJr8sqswhZdQrYYKeimZaIwNAVU+day6dG/ObTi9zSAcchsra0SBBs6a+E9NkYBpKjJPYRnK2NmIfvhcbZevwdIzihA740sIsD3/1kCOezAUXy1NgcS8N4=,iv:nkL7BdzY6eKB7ZsazQo7cXIxdnFiAUAnCgQWGnkKffY=,tag:nacKB6MuRWdgObb1EXAbhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
