apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0bJVTF5KYeWJjS0zT6OnwYdPjHb1SIZcyXntlqgzltaOHz56LL6BryZ2hBhg2bP/mQ/UdNDz1/rER1rbtcmppIDvs/3KvUfdVI5BlceHuyk8yPf6dqyIQEn2CiiSwB0KcOATHs4C88yeXT9R2pT8Onv5tiAS7H/v55t+0Yh5VX2RVdZQLf5DJygYq3oT0h6d3tjqeb9+GPFl5E7IdAHIqkPCP0KQeW4Ka0wbEF/pg4bkg5jZoQnSptlqbUC4hHQsGNRWdSjcz7zgCy7fOP3lhPvbGro/fUzBNh7VTrq2Hd8dN6lPpgQU8wuovrXpWm2kZ4lvjuCeP1OKxUOTzPVxqTKyabYlioUDcgiGrRitwoF43UmdeQMf4kojv2eYuJwf,iv:pB+WbI4dxosXlGjj6qaoykDzB0lkZg1LUiFYlNWP/KU=,tag:0xkswOAwO1MDD2n1KCR0qQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ptbU3jhYlwmJdyyCAbGkMB7DI0vnhSzANtwT33E3uDWxX+mzQvlGqmTEfAFSqTLjvOvMEtIFBb/3ajWOGOeBOqSiavhG38RUR52Z6U0e+GBodYcCdHKvhPiZ03bRN0oSBKMmCCBrN4WcsJwJFLbv/WFokXzvf9tXOb7xNRUSxYAPoCf8ZigNdgpwUDcPyHTRA0T/SXcAGTK5ksO+8jFyNTNOdILND35Xh574mneDutAsRfSQDA38PlgY1LXQKpz113uGulhJscsQTDo7Fg==,iv:r9ff32SEXUlvHqCRTEDp8ciEnOIhBwvQbsAuyickeK4=,tag:Sta6R3DLI7Lt9LnzGNmhcA==,type:str]
    known_hosts: ENC[AES256_GCM,data:1bsNDplCHMLkun6KP+ZjCc0lES2H5yQUPFb21LXSM9jJUuTQXYOmyCtAs1UMf5NS2/ZtbJL2KGtLiN/GX25fV6kz15EjG/yIWbDTN9Uc1N9Pl7K2t/SkBBy0EqK/UY9lQEAwABgcoXUHFJ7eBDNQNXXRaxMl83x9RKEMv5qVBXvynEIpzRLRBs69IXT7VKEvqBOye8DOBHQHvs+bpRcHkkpsTlbHahz0rstC,iv:v5N0cryPMZqdZuUfCV7wBO2y2usxjChaEm3N7LDeRNI=,tag:29GgazoSn5nX0TIlxEq0Sw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMjY5R2ZQcE9McFZDREhH
            NHJ1anMxck9wWVJxb1d0QStRMElmYVY2MUQ4CmJ5VTcwNi9EVmY0UDhtYWtTcWxo
            MklsQjZMVWNub2x1Zm5KRXNZQkVoQ2MKLS0tIC9PNG9CSWtMZFZBSi81eEtDcWhR
            anQ2ZDliUFlFZXd1ZEVXT1hlS1E1T0EKwN7mtSrEySmGbT3htc476GSZyyPciGcF
            Ynk4ruvICWZzKWrYiabtqE8rH6URab4HgRRKDzSMw8teqzoiwFRmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T00:33:51Z"
    mac: ENC[AES256_GCM,data:k/DYlwPSZfTCbvqC5dUusSke9/QBMZI/9BUceqDQ1afNkT/bXP6/CmEnRjG7X3/5LdtA0V/Ib3U0dUJR3sGq3XOOwW79VbzY68SZYWIABj/W75xzZTmjro+xN5t7lqdTxzcdZwFjLMLhaElDqQaqnLHGFibebymiRdoJ9I54H18=,iv:fxQGkPUeQxs3m5BL5S4RYyMnpIL9wixlM/D6hUwkYto=,tag:eZu2Vwl6Lh4fPHzdgsyL4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
