apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CckW/TeT9OVQIQzd2ttKFmkDIQdWltIMpfoi0gLYT5GDc9jH7gPQP/55RFvitwyvWMve8agIPfgx4Iiua3MbtILmREvhY3PNGc3tgrLnff8EPtCptSdg0NacGpvIWOJEH6awkpNWJXTbGEyqqzPVdwcDUZNNQiklHIr1jgRtu7k9lQqQUQY1V2c1H3l6NP8ylb72Snic/G8mJlhK2oxnDyBwS0kdBjP0ZD4txcnNJZ3snaFsgDJNCOdbHeP3xLmovDEFx3/iGesEyChoppMMdiDac1noTdy4VD2e+sysKLPntz4gO0Df3aj2vdCIDjZIfivJUaLGPvNN+Rm6IghKu0PHI1HrvtJoeANKf7iaGIBYndas+CeGsHICm6pAHzA2,iv:OlOehXJLHK+nZDWSM7Gs7uOL6NAWdyg+26N96ryas70=,tag:tHCuYFxl22dlYhNzni9Xow==,type:str]
    identity.pub: ENC[AES256_GCM,data:1JilJRotajCd8TYwq9Ee5Qq6gFBimh1q9IyQcC3TVd4n3h2QShO8shM/NO1T/fFp3nia4P1Xv63zBS6Cipq8ijt9IP9bu7W6ObnBa128nDTWlz+QEtndUm7WprPEahgPdGqFvgAfz0MXuvBl4dj/V7y0Ng6PnosTRtpRBo4MMBq1haY0eAWXyJD5sULoeQHqUWk3zWSOdnkEeHQpCcWalA0ZW1vRgAlHzgNP61ePRzaMWJGggUYwJZRZ2tqjZtUYPEYx5B7Tn+VOqoBk2Q==,iv:qhtCKNOlAxn9nKUh3MFe4PKzPQe/5tmZFijOHRR37Ds=,tag:XiUCHuyiklH0phyriGgVGQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:aDZaVeMj0hqTz982k+XysBOXr6lqLtkTjPfyOXPMsXS39eVn/x0plGlF9D3yZOQqEFkQA2I8CSqL7fSk/6kElNitiIRIR1IKywTgn6ZiXUEGpXN59f50MW3sZoth1FL38C1SO3liDnWOxuAx6E0PwLhhZLJTZNbUiMaohOWkI9TF8Omb3rPrzsboZgB0PIGSVi1b16aIga/V34kb/WTwv5gR+wpJUTpbY4Bt,iv:AaHTSv+B/D/yfEMaepfxrMFcrgj4Iq2eBYPFYzzsgXo=,tag:80cJo3/7T3HtxlazhYiWyw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c1VtbmpueXFnemhxOWVU
            K2ZOM0M0Wkg4ekdkUWxTbzRQb2pYU3pJVHdJCmdYU1pUSW01cWlRUWFkTlJFbDF2
            ZHlxQ2hFYlFLaVJ1cVQ4WVpYNTBSWHMKLS0tIG1uU21rZWxmdGtVRC9zZDJiamJ6
            cHorUnF0VkhzSDk4MDcrS0p2cGpqbXMKzE9Nql93fBduTIvA8x2yFyDDUEA5j2H8
            26a1qpKXBVReQcE2TOKVprfHRe1Hk0gWrYnbC54H+ZUqaspU4tN7Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T05:33:41Z"
    mac: ENC[AES256_GCM,data:3ZAfALF7QCSXk5VfHM5XJsA3xn0zr61DVMAR8BPh+Lb22Bj7tFrG66PHUCtSMI0bqzxAoNSvz1nBR6y5i8hSOBDxS7awFCEFe0Gn/+AS4G+uy5gpkZHarFAWft+Fv0NwGZA0onVpcFrRogehIBIw/+WfJq9WW/e/CwjmJvPd+yg=,iv:uqCNGlT80ejgAo6GANNiBd0Y3rpoQi0ApNTVv/gpKio=,tag:UOsgXTiguIym4xUBc0GK3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
