apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HiHlQ7/JHUZdRD+OpOcs7gyQOrGMeRkqlU4BsOyCsE0f9Dya7Gg+tpxlmQfyZtvDQL0a01yoES/R0/7tR5zlEMv/ILEweghjZwbTdZ5NqCQ05ezsfh5PZNv4XTV1PMfpmA2OpN8zj/jcL6jPqUAgg+Gh2IA9RBE6dEUfQXE1uOvL0syBbotsQ/C3QroMN7BbchxI9ajbnLasTDGsrLXWgJDz2frSbvYd3Y2nQySbXKUUQDsALw4k+is4ShP2nEDPWCu820dpT1XJEIo6jrFoZyrxkPIxAFBhJza7jHnrHjXPKjdA6m15FFEcKzCf1Z2JikwIDLr3yQS7hORthdk9IA5ybYYjLY4OeEClVq74W2nczM1fqFn/VzDGCZmBO8gf,iv:/VdE6MOZacKmn1EmvPGVirNOXExfUU0kBJwRDBOE1dE=,tag:WwQEENaD57cIMTGsOqzuZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ot2F2I0LOuAdgZvUpc1Zx2enDLSbeI8QJeDUhbrE1rPDMsaFc2YJSi/pp2Nx5dpYhReqbFvPfsf4lCpXBBCjjYcxUScrlugFGaFdSg+cLYA/ivy8DxruSJCQkXwAkiZ8U2crxgGVmZl/7JsEQUIyuhBw6iZtehUd+uakexvD63T2B365ALpJkQLBwGYfDf15hvSQgsHEWhsXLTVOycbtJY730O/fYS/K9l2aD4e+OlGgQNDJQBHpzhhZ2nzKDqn/0p15IuCg0wOFCP/opg==,iv:NEZ++ReSnlfgoYnAnAjWo9leSsA3K6L/46zoFz58Ils=,tag:YSMuCxAkVhFE07UNwrTHqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:U9rhIOZfyPJgl3bSyo/zuf8jRRgMQBLda8Hv+VgPR2igLJnScQGJ/baPNjS6guKTWGeSssUPsm/oZcjxaOWycR0UjYCaRgkKkTWjA+R5PpaJrRl/SFG2tNmpR5z5slpr7AutH3cByw0SgEAZwp/D42YDMTl3ALKm7dj9Xdv9SwIMslrBupsS2pggf51qkBIKAzDO9ej02tMcTw5iMgOM8j5kjcMfzK5CWkLe,iv:PRKomQuC2wkRV4FHUDeEa0dtS5bxJ0tcxuPP5oSyFxA=,tag:ic5iDFeidKJLWZ9RxiXPqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZjBDU3QyQm82UkN3OWlV
            V054QWhqZlE0dTF5M213Rm41TE1UeDJPb1UwCkYvMkZWV0I3ZDBLUndjL1pITytF
            eFRZRkR3ZWprWDY2ZDJjUUozYkwvcUUKLS0tIFdiemQwOTJiVEl5dGNDWWJGSHRD
            bnRxRnN5ZVZaS2lFc3Yxd2IyL2pSVncKXIvxHlchkbLnqV7IldruyppO/f++nOqr
            PlcsCWmW53sNc+kH41Hs/oaFdndvQkL5eR6P/rre+/BiiCpzX85dkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T17:03:42Z"
    mac: ENC[AES256_GCM,data:FNfD4Jqfem0wBFvDiMnohZQuPgg/rIqqhTQGe0DJbrCaAIGbRgMpIWtoixvNODGfhTuHvNPC/K5Ox0UYrNu8AAW3qet3ciNxQ8W9JShtb+/MCEuGrxhBM/QCggkGbCe2IPWwlj2cPCbzaLyv+ePHBuvAT3VkhZfQyzH5ROCd7AE=,iv:6EdWvu/7yXQlXkeTGU3utdJFzjKoaF2b3Y7YaibpxCI=,tag:sJ99beRYfX3fkg/hUpz4fg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
