apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:Ehnz15OWvqiX2rsPUSD5ciuKX2ZgD+wIy/8NbA==,iv:xHeUNJ7uRnXz3ziCOxOEZB09J7nMOIUG4I5gYSZ8d6I=,tag:sMFMg7si6MQyE2w3/AAQug==,type:str]
    settings.yaml: ENC[AES256_GCM,data:Av96VagXZ2h5S1TjhknSDnDxEyZhHVhG8fi9VRR6t6AxH8EZrmRyPA+x25jMU8oWwDZxN3uFaaaiYAltu8ZZAEqL/qd3CdvukQIRAFvfF+5HXURMJlYs9cLprXk6a9YmF+fsX89lIx+p8ZWz+1gbZ/ar4UQEyx7Zh7novguUwpdQSa8hwVPHwcZ6tggsym1/Idb76egHlaRQIsv2+XGvqDIkt8OnNdVjhRPwALMrSx6PlzNzE2RrnwUd2lLyT7ySB+GFS88O1mje1ihMvW0lpLJJQXfxFMS0+Fszq8YR4CzGkYKXtGFS6ZVZo2+936Lk5fgsBfbyoYR1YafUM8fmRiukQP+1Ni6pawBJq210R3P1lpX66oenXBXAjE+U1mN6AnTsqUahVKXqv61jylm+ryQRmpZv7HLCqkjtI2w3ZqwHu7cYx2+xTj6251e+UvaJBy+ICIjoMVJfOeE4xs61YXJNOzCDuP6nuEShGhGGXHZyi0OQ9f6OEZuHM1Qd2aQU+20F8CAlR9ha7NsufnqK2GT4coO/p99+wgrqZ+COqJ59DeOZkKe/8B3WJmG4M03e5FfASM/XwlG91mi7NRVlvXKaEuveV2CnPc4CpGEicd3EWkBC/DM3mNMfm2k=,iv:odzFTuRxVWU7RP0zcdjjp0fC818jVkXSK0ihN3mqS/E=,tag:N95oMRvxXg+TQlr6PS2Rww==,type:str]
    services.yaml: ENC[AES256_GCM,data:PvvrGrBZ58R967kqYafE/Vm74dXCbw0LZyeuipN7+fixJzMfLi7pbIPeDAxG3JcmmVdLUyKtgnBIFcDTF6nIJjivuZbKrHUzKOdPz6ZvKex7j3e8S8cW8HkN5bwCKItvBG7alJV24PIHw4tuMSsAxW16zNEv0czlHHd5ZaRP7WouiVIvDG5TfdLPD0qK+93NDOI/ncr2NM8PPCGufQ==,iv:vOzNMYZtJU4HnVXPZIkrXu7IshGI8vjAgYjhdqoTGnE=,tag:0HC8gm4IvOPebsyqHOXhPA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT2E3RU9aWisxQXdtSWli
            dkNMQ0J1MWkxakZyYk9JUkF3aUxaQXlXV2tRClZwWlBZYW1tblVYNlVjZE03OE00
            L292eTZvaEhkcFA2Z0ROV3NybGk5N00KLS0tIFNDamFOK3NNdUoyZ09uR3NvOGJx
            NGpQeSs1NDl0N2tJLzVQbStUMTYzNDAKm6/80K1bX8u1efXN62d214zC+BqQ8mM+
            VE9+fF/wWc5G8Hr3ot3T9SFt7MJqnoaEWzk92+tbAIqS8bceUmYrZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:44:43Z"
    mac: ENC[AES256_GCM,data:P+CRyQP5o7Mv6kS/kb/sFIqqe5oT4173b4Uo3nrvzR0K7LXOeeIQttY2PjZ39AmPqyWPnVu6ifpEWNhdfLKPqEc5shZ7xE1PZbgXc0/ginW3h6KkvKjiGTDt1pfqpB3L19Mbw47P9I24dQGGPC1sGcx+2FN/LsXaUgG4OnJOodY=,iv:QwXuMbszs9aa8bng3YUGJ83N9QvSXIPJ0TrWKFdrZxk=,tag:HcAikHk/zWgd2NbaDgeU2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
