apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:/TOZRfBMY8DtoqS4mj1Js6M0QH17HvprE+rDRQ==,iv:pBcwBZXTcDC1vxhety7p2YFyGT+ODk5gsAulAP7c06s=,tag:bDaqB0+VDTJnGojlkZzQSg==,type:str]
    settings.yaml: ENC[AES256_GCM,data:PxmMqYXyR8h9jwdPC612GCqv5i+qyFHGKnv15t70+S28NHMmLwQ2/yQq8Cicc7HUz3uZS1oTw6I/T57H26dtA/FNW57SHgHW1rSzLZAesbBqQGf1NVwbX9IVG1NJs3Ds1tG3ncRDjAlJD9vaHVn1bJ8l/fqUU+vU7eRVCR7a3v1N6sm+8Mmkhx0Tm7pOqxvf5s0t2yFD5TZn/yiOEtqCD4kUKAiqNoKqgOVIvznlgedJyhvAT+1TUhbibE6L7+eGW31+JyJny5Kmq45pz9wJjISl0IneytIyolhusL748zXNo8i2TExoa6Ku4YKYG/2NO8rOPWxYHsIM47v+8PjERGTI0nIBX+csD30vlVW5K5slOiRLgR2q1kK6E5DDH3vFIhepDyOgku1MN7CNX8q7n1BehrJs8ROeaETszYPKXKvBsqqsqagJOPHGzT6twz/XiNreitljvFirc/xxIUG3+3UT44Qk3ys3xRETH/Hba5ZTADBFgCWyV7FyE8vzX1PZYPxbho9lHybum+wMApnh0zjsge2zVIn1ZF4esyIfXer/oPQZ8pzwR1UU1Ftw1Siy/WzZPyfppzXa6trrt2kv9dU+hcvS9TjWzbq4l/jo/rYQs9R7moKn49H2mtY=,iv:1nnTq48LKDPyOeR/55BwMIROoUFgwRUNveDARJw2RAI=,tag:P7rCnQ4xvNQrStmIWoHOKw==,type:str]
    services.yaml: ENC[AES256_GCM,data:zZPLC8xyjgpujb25dYDjqp2S6Sr2HClYb4bE646q4bHi/VJEB/fNG5VFBnFF0+2Th0AThgsIIeUqwtJV4SVSEidOBJ2HFR+IHhYUK0dTFNZb/thmA/glDSMLG2S3p+5ldSn5OXqd4BBVhXJE60Zr2yKnqyoO3FMM94ZyGiccQixk7Pogj0Z1JNoGQC3KWBFiocGyFvn9ByDPe5mZTA==,iv:mQqmqsfYU/UZ9xJh+u5gQwZKzBeNGiKzi2TRBnvOgKI=,tag:g/lhygzFRmZLJylaENjyKg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0ZoT3BneGZLVHNUTEFZ
            Nk5ndmdzVzhPcUNCMWIvRUJDMEsrRHk4MzJRCkF3TWhaTUFqYnF1VDJSaUg2TWly
            cnFlNEprbmdHbWcwQWYwNWp3c0NuMWcKLS0tIHhsdUhyRWZTSGpBQnozRFVCVlJx
            Rmp3bG1ZcHcrVU5TTE5sa25YM1NKeUEKa+LGA17PVdFnRIV5PuxywXNUZHaAniUz
            pQ5AiKFueSoj3oQ7Xgba7Y8N8hHQpj6ixBCw/H0uMeAiEWwGQzuUDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:29:49Z"
    mac: ENC[AES256_GCM,data:zX192z2wNS/CRV57Yhg3ouybEYayWR6A5f5vTKXbcEQ9SUQAV1lof20/bA2txtp5amdvqJAwRNNYQ123SoePrc+Ua8Dm218kra09HAICYeUYYv653v9Iu5jMRp+j3jlejb+Ov9RBFFP6RH8/Qn6UTC0SQg+PN7cZkQzy0FZAe8Q=,iv:1yj/I8Nq+v4xTgiTdkOTRogEayJ5XsrGJqHjiReePAM=,tag:Puf1o3ovuWh9rEFDwPmz2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
