apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:EGzo08MuEYRqURaLDoXRNkByoLeByfbzjNxFgg==,iv:nwI6g2o70+gWmkBULPIqzSdU7h0Z68MxbeYnijwEHss=,tag:PxaujnEln0F7bNaQWB1Muw==,type:str]
    settings.yaml: ENC[AES256_GCM,data:gXksVgmoX1RqwxQoletAMWkgxtWc0nBoQD2U0vHZH/MqvLQ6x6cE7p3p97Ecy5YqoMn7GB3MA+agb0wyWtNkhr7sD1U6kGgHlU3IW6BJ268ujFQqs9Ey68LihAqMPOexxNc4qIN/exn1B3K6b7owO2L7X7Sm3o1solfQrcC8ollg0geOSHW7FSLMLxECBGOM3/89tvTBcRG0U1GiNLUfBq2kDxK2CHLuicnNgusfc+5OQ8UH37IcP8320FqoFMlEZpGjyNOzR06+dcsZakmzKq/zTVqIwG0Cz3mBDt/jsBdeAVDYA+ez81wnG1MWEorrGRfkJXTz4ILTx5vSUYsOJ60xyKf5mb5+gxEBY4vtlH2Bt3Ai2CHMCM/fQUS03wQcHE/zeE5Mwlyl744iyQ0tN/4uQ6u7XB+TXhxG74l2PjnNnv/3lbEhxL1OKI78KE09WQffGnu+dwe/87NJVGPGbSSYDpWU6ZIEHiS9GlTJC5t2Angjq4hmdLDKexZrOluSpC1tQ1ZFTBHopOZLoQTY6n63gJIsICo5fymzDbqXuSwD+UzHTcF2W3Y2/XHLqLQLulM/wb/K8SCIkhvTAxEtSOtoDwLoDTKSAKtxWtVxfDRsyFKj2QNOHSJNdtA=,iv:guTth7cp+Ruz4dAL5xkLZGsPiAY1vr1nlvPF7QmlDmI=,tag:Q+/S9IUToze1KEcS6uVFQA==,type:str]
    services.yaml: ENC[AES256_GCM,data:X201bTAZe80X9KIlFxLnNlzPCspKSZ8NFF/imcLF1yXxX3bvSxNCl2g6lWqF1ae7K9Yyp+ejKRU5WW+FgAl5vEJkVp6ODd3DzACYPgtQ96cDij8u00nodebcwTpIVPqFzKOyTBDZmxd5iBVy2Z6WdMehfocJs9OeOU2H9515oDk+2Za6ofc7N6PdWspNY4lBIF5j7PoEt3Lmfhzx9Q==,iv:QaYPTUy3J43qOxun+TWSb4U62TP2lLW9IT6qpqBH4n4=,tag:tVzEU4YSJ7R8/00Hsp+jpg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdTJXRVN3SkpmUW9ZWlVq
            R09sUmdvRXRHSkdLS0dNaWpHQ2dEKytzTEFzCllTMDUyLy9RUkVWcC9SbmJFc0gw
            K1FhQ1dBNk5TNTRGYSsvRWNZNS9UUmsKLS0tIGo4Z2Zsdm90YjhiMHJKY2l6ZTV5
            b0lIdVgvZjc2SXJIdTY4L0xVSVlGdkUKHQ0QfgSq/N/CuV9F1NklTajRZdAGzrLY
            O/qUAPbB8pc5mDw3XmjFHWs+ZNC0wWQ+lbcIOtRs9JkpLG9nGl0+XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:13:03Z"
    mac: ENC[AES256_GCM,data:YgiNOj9oPvtPDOo95H4jUFIGYFIz9zfksCUg+cPBSx42DVfGmvxtTAbaHwQZhwrap7Jke5ybDRwJzRsQPojcjD8MAeEu/HqtrzcKJP2HdZmpUy8D+PaN3G9+tCgkZ0TK5cWIBIpISDIp4X4ywKOfce4Bz/P6e65B5Pf8lRDJUJ0=,iv:txlvmqwNQNl/1mymV1stZwjdyU15K2+G0iSvDttIBuw=,tag:HkE7sSqvadvHRSiwRmqiMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
