apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:+foWBEbikLf+BFmLwFfT8l0fjA6lCA+dkG94NA==,iv:PL8XLW0WPWOsajyfLpkXMwKnsbI3SgSQgFTSFAHyNn8=,tag:wREtf17rBnviCymVVsgWGA==,type:str]
    settings.yaml: ENC[AES256_GCM,data:QvgAfR/sncOzVO7Ya/a+AhOFrnIXtM6eua8Yncxlw8a7gT6uvldXCUPmfuyxkR7mmF6Ivj3mzriNDUm1C9GVjfhcIe6txlAW/ini+rYaXA0KCjrOlQycy79Jmtd9cpd7BDy0FUfRqQm53qpCRvrVyH49TilRwhpj++xloOXzOw8w86UuS5e2HoEOvsSRf/FB/XysiKFCZbEtEEAVDANO6X2m+oeoJUFA3hMp4tJ+Gr7MhjIi0Ucfj+vrHm7t34du04tLVThql0+t+3puzI0J4RIS+xKqoP1DJDX0T4Yz7rE9c33Rgpp9bRA9+zCH2T9xHOeWScskhBvDcko34bdmnAhQlSSkl0h9L+HFesjjL8SeWc1skvDeS0zXM3qVyKgkYh2UkvRaIWJHhwfWs0ANOI/3f7+dx/BxwL+qEgushDF03JPLw40SyL/QT6zuIYY3ZgAJLTNUOtP4xTU4vtbqmOcSJwLy0SUC166viVsFVz2UTwvv7fVcjQuOR38IrRBPVaoB9bJ2rXvxP1oI6KirzXO+d8MyFIDZII0wjEy2LnOL+llulkc9XTcQ+4YddpabFfZnOZ1jiIkgPr9a56j+iNYXQinSCytbSu1MWm1BJozV9rydLKfnKzdCuHk=,iv:unUIrw+vFpgAGTyBYoUM89myY5S+hFL6Tac0jlCbl+I=,tag:erBpFUYxRdRcwo+g3GF2VQ==,type:str]
    services.yaml: ENC[AES256_GCM,data:n/szwPQ+BYMCzUTS0xCtM4d2He8Up1B+LkYUYhvoUtkFsySdPMHKOu9DhpnrEjqibWTp6yYEA8BYJnNkf9b12nl3+JcGn5f2aO9d5xYbCFFTnqdWf0eZ5HSorvDh/4pOMwOs8WW1k/3zoK0oCmpVq1HrrS52c+XjO1uW2ZPMnDkreulzePi8E7ozSDxSNAK6YX5OtsKPS0Mx1Qp+9w==,iv:UFHJzb6w7Nq7CFsS9uIDCexAEHI7U6HgUINa7iK/xtc=,tag:TAW1WtFsGzU1r1Zjg1fYQA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbFhkSjVXQy9lWU1sQzBG
            WWg2SlpDdTJqLzFsaENLNzhJSnJQL0lYZTNFClh3NldKVVR2MWZzUld6Vys1QTB3
            SXZyZW1CQitQRW1QakpQRE9PSFVXM0UKLS0tIGJPTWprWkVhbGNmUFJ1aWY1Qnpr
            TUd6OUptWmZ1MVArSUNrbHpvbnJsRzQKs4eQBaeSs44oLcGoF+k5EI5lmCsdl9xX
            QGB1msbYneSQLhgzuFpragNu1YwvcWfz7LfeZR0Pi+bCerwOYxP9nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:10:15Z"
    mac: ENC[AES256_GCM,data:LMd0fYQzFX3AwWIB7HtGQe8A0DhE4SgKMfohPmwSKFcQ+OUqIUb/rcMFOw2PdY74Z+cicLOAxUk4DrMq0MysQRmxX1IvIWeCXj0301N8HQILEAFY7OMasTDi2Rk11ZgAgP3HT7wJh+zsODmIi8OqgSzu3HVCsDwIuJiFEa9HS7I=,iv:th5feoOMIqj5zXM366H4R0+wMImdMzEudhtaRFqmEkM=,tag:oEo6vsvqXCsxRCxXMqIZyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
