apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:9x4Z/6lP/g53edP1lPmV68gAe5FOGkrDoak85w==,iv:Cfrj6G+h1iXGvYhZuqBh9qk2DhkG6XKmoCNED5GQKiE=,tag:HgdtKcC6OH95Sm1yNcNxVg==,type:str]
    settings.yaml: ENC[AES256_GCM,data:IA8RGCejQkAojSNsV822wz+t04z38U1NSfZDa9ggICCwzRAbu0Sqah5wcQehpSzU8wZCaHKplFsZ2Ck/9WiP9ttNKA9rrZ8m8oVt8uVhow8NqDUFYEWkDsO2ZpI+kL0sRa2G6a+rMJn89E2NqK9vfRFGR5MSM8dVXXor6XeYFYUtd8pWqdO89WQePAhP0mTFLANytDjZUhtkA+JccFMgrKMx4hUyXuYcf/rjQNSMldL6OxCdjODKR3Iwfv1wKaIB21z8ETKKrXrZv5+THA75QMDwlV+TFLCGbbQjkysaZoXs4M/yiPXg9YZA/2DI7KIqW1Vfo23PzrOFL56Q4zHZmctTmIBeDI+uz+UpsRAoJ9tJ9zyg3+wfN3jycODCBIWzr16VXIeckU4TJiBKdgs8rNQJrBgZXqXMD3U/yljKe/JrBCazM5zYWHVeGOPcWunDEupqdtW9CX8zyb3X/xmh8g5rEn4SY3vL38wV+1rt7fumaTWvRg3RWbXeXeMgpagjTC6lyEx5gwoiPRkKdnzX9iSQtHbyopLXxGGiSRRG/WNyTaqvDJ/82SBHxfzGbNL0qReumJsIpVzJE5ux4Z+R9vvm/8CWkmVxExOy1Gu7CM+f+h5s/SjzNrd7q5o=,iv:m7R29Bc2RZu7deS5wf5NgM23D47UyS5jN0/40ZXl3es=,tag:u8I90A2Lr0bNOC8i26OlsQ==,type:str]
    services.yaml: ENC[AES256_GCM,data:sWIQ82/FtIjkAIaHUVPewLV1VA5Ui2mabfZq/091U2+TesFUU5wx8LVsAL7z1+IxxCNP4BhOfDMkea13Ve2SyOG3KXY8QXnrDyABT+9xnF1AFZvdGbSKAGkQspC3+tJgsZKj30f9LqdDkaZvMfHp5CENiueEbRuUW4xMVrMlXvNO1s1aC+m7+ZQqG9FrGSzk4BrsABnVVVUClg7w1w==,iv:e+rsJ2r7/PM6dmZbUYfi41RA4fjxqS6NEww2OJBpZxE=,tag:3nT8x8PZVla0G8QiMdTitw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS2VGNWJIc3VldHpMSEU3
            MTMrSmlqK0lGR2hsVm54aXR6bzJTR3dLcldnClAzcUtWTThDTEFmSlVRL1l4Y0xR
            bmUramt4aCtGWTFOUXhaK2tyUVVIVncKLS0tIGdvd0hXUkpZRzMwc1Y0dk9tNVpx
            dlFjSVMzdWQ4cUJ6ODBCbVg2dW1KQlEK/DmMBXKv8O7G4Qsoy3di/B3LcmDoCSLx
            pxg/utfqAs+Il4JbrVEHjd8EFEalwMzwCKWrXTOGJYf8mnW79KTf2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:09:24Z"
    mac: ENC[AES256_GCM,data:KnnL2xnuQyeFY1T+v3ZKJbIGlg/OLJB7BzKxzDY23eISzijhLAFEL6XL8Mb7T8iJUtbyN9rRyNmaNVA19Mj9mZidQ8AfL1DuDn4Nr26IjMIOvCGjEhjDMObMjWHfp3HV6jjE9mGnRpkWgMNGFp5MPCDm2jD6bx3sDQmqIDYaBNA=,iv:SilsN9UnlRByN6234AP+WmgMlttsXs7EZJsFrQLpUvE=,tag:yIcc7LvwSAjgYwgEWGlisA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
