apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:kIhbCFCNgQVltSJap8MwK2kPhh9/9YHJcYCe3A==,iv:/O5oopRecWDhHuZrY0UWsczZ8zOa0GgfMD/J8Lt8+L0=,tag:I50m6Wow3pP/DYoMWOfmsg==,type:str]
    settings.yaml: ENC[AES256_GCM,data:lZhKuF72JIq6VOIHSxoqzyDFfFwl6ximtnbrTz4LppWOxE2W8ynwZwCoGqWBvW24pqs64knrS8VK0JeE/1D4R2fcVELopuWHYSZ+PW2+LStGhmJZ6OyyCVXhIsnnt0HwiMew2BOhXyizwAvC4wU7T8ZbtL/Ry8bqG+W+owyjnrh3PgCPSo2OqtxuhT/xG0hweVZLnZK3Zm1N8qksEIEtr26wpPDY7fKyiIoIATY/XMBKhBt6qCH4upUI+fge6aVH+dT9nlQtHQx3OnVg4umQlYtLpIyZUu3rbRabyPJ26V+zcgYn+2VBPdExJyn3Gy4L2y7ixdhq7hzSSZyUdvVOxmZnrEji2Erqi3tNf6rgdTwOJcmNGLgj1pLZ4ZM3yNoV4gfPUubaquMp2vC5Ev30VyTbrKzGuFp7XYR6npxxI2lgag7UO4v1zMStcZOmAnZeZ2x5YQ99aXiqrlyClGzj83gfFiib+RZszLPL1ra2o9iuxUAR8HzfATfR8FONJ+5+f37bKQ7Kexptuxi+xWvQky38M7Nwxefb3P7rBYQeFTKcFbLpjqg8ViWGqHATXE5emKY9zmMDHPghGENXgsoqLNciXnL96AcgkltGl5oZJimBgHVPF5NEwCM/MP8=,iv:BkeMD/DmCPhSRi+2vt/tG389Yrwp1AgEVJpeM969824=,tag:8AS1KdjpAzUyjEs73GCCeg==,type:str]
    services.yaml: ENC[AES256_GCM,data:6XCFx12y0nUbyW67SG204qTkBvnY1Ey/FgNSVHxCSYuw1ErT56Nu1bwT5h82RsY77DOxCLvaQLJuFiyq2Isy27F1C0z/CcStPrrAjzXUWaTPea1ezgN7sXMWwKycJXRrjE5PGlYJyvdBUHBM2+eC6C3PRr8QZ4/Q/mHfuy89/2zPQOGZFmp0g4+cW7Yy+HIMMUcyGiIVnQZomYur8A==,iv:cq2GVBGvclHmklERjsxY0Qk3ZVskg0yWBzi2OaUWIj8=,tag:UDGr1rtaS7QCeGA227bJvA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SFM2d0Vuejgxc1U0VHYr
            ZjZZQnZDbEV2Tm9aM2NocDc5MnRENlhhWVJ3CnpRZ0JTQlRhUUxVeTdjSlE3MVh1
            QUh5Yjl2bzZUMU9wWXZYZ2RvM3duVVkKLS0tIGRFbEdqVkVHZ2ZqS2ZsdllYaUNF
            MUVXbmRuclJmcHBvbmFsRjVGUE5ONTgK+ZlfOerhE7l+GKaxCYkKLBxCctLTjRoh
            ZrstXJWtLldLucKds/iuFyMIMh18raYTVxVDpDjJSCog4o37JAE1TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T17:29:45Z"
    mac: ENC[AES256_GCM,data:Y9UTpdyDbyd4r1OeGmr+0X9hQGJqW6+83lnhIQyqUBzqkngdsD0pZyh9DFybY6eJik2r+CpiJrCkSiSnjEk6pHWoxLoSEfsXGrVdkN/UIFwsBpL2QFczHqBsB8/Z/6X2Q8wOvQ3D3fm+SsGrg9ZEvdYSTEAfHEUhdxdFakW5bD8=,iv:O+4T4qDgK7Uf8TWC6vYpofEMbFPBNYUvEYREJnJlVJA=,tag:oD68vYFK0kv1b5/YCatW5A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
