apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:Jp9M+ecm0hgvz8akIgdzoE+hD79dkmeUL5yvIg==,iv:kXTSCBag5coLnXKKOfYYoPE5O8KvfPtRNAMeU8a3ciM=,tag:ii0Mq0SW7i1MROETqD0gsQ==,type:str]
    settings.yaml: ENC[AES256_GCM,data:xwA24knunzFsSsBRlgmmkM7dcwVz/pxAvcqAQCOeEn6TqhkC8QZos34PeOcaWSvqgmMAtfbC7qPM/c9/hQtf5MKcKNrEWfStbUPxhd0qZxd2HEspV3ZECRpNhhDoB7DxpBx5Ya31o+TL55FB8oFJiuyDiCMFXt0NWTZrC+MThYF0/j7hPJZCcyoWr/jIUxrzeAg4/YSQgv4iwEKd8TDpneSBXWkJ6GfWzz37/B3e66sOoRFQMy4oCRR19ihvXbBRzkdh8G2V+Jsfc2mHHUmsgXrTOMwPYDhy7+9jspFK5rx7BvF4VcIyjgjda3ShiicQWezNyxRcPBcxTFrK2j0LainUXzKgmNxGyy0YuRwFGzW6QtpkbmcepzWZIFLQHQC6GA8Sge7PmwsLZZrXrtl2yX5q7AebJl6f63qCkzle5eWrtFz9+uOLMLaEVECPkBJsAbCVW6+Ji6Awp47yoW5iW+wm4WkM8Dv26aXx9GVKS41fLS5fmglKUcvHb/HL9LqtoPMsvfTYDxEC7nM4iVzzb4janTcBY+w7zpeD/bACb130tmacFp+fez8Ru609SHLSCKbgUQdh+s5OfpCo/Tg/XTVqys2WpBfyp0UrdmoSZUGFMlKaykwgPtOjFds=,iv:4Xf4rdzm2uWaRtCq+91IkEgV9ePuW8KXP+54dvP33sA=,tag:uK9i1U9JsKS6EI+ceTezmg==,type:str]
    services.yaml: ENC[AES256_GCM,data:SeV5Smv+yHOGfgM9JIxPAlc8PYV4oHKJabOrXJmnl9b/mOOpQUQMrOgQpXC/0EcvrfhASIW6owJWdbAlWGq+FMd+8JkyBRP9HKNxBxu/lyqASpk2bVz5SZXCAM/7bTVC3D2OEFxXIxYCYt1ozR+BL7jq0vGLL+Rh/MVCSO7FZditL4/GqUze1kQ9UMKfH+/uaH3NEXeNvO4s58T38w==,iv:8ISv5cVLPEjdiyCmfT5NkkhyieroRgE/TjwIB0xi7NM=,tag:vE9DfYdO8R4Lr9Lr/7alug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeDgvWE84N09HUkk3d2Ux
            SnROcG00Vm5NMlFHVmlnQUZwMnp0RWhieXhRCldVNVJOa0pSVjIvUS9TeDFpbENR
            SFJrbllKcERqSWR1WS9lWExNZ2dHS0UKLS0tIDVZcUdmOHdRcHJTeTZKeTd2blNh
            UFJicDVpWU9WVzNuQnAzSWNCeGhIY1UK3mAqz7zUierFRMYqa+lddi4M1kKWGAOq
            K2t0j5aT+sGruwwcj/sHepdeGqAEx7DbkwvMusAhkOgxcMcSI6guNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:31:24Z"
    mac: ENC[AES256_GCM,data:Arg4LHcXqDqVGzvTYKsAPYscw5Wpf3+6Mnpy5r8BFptxSbjWW/jOT7yjhuMc4BxA+2PZYxaEQxR9TfzcoxjOIzfbInWAIszSrgvo2Wxw9aIEqb7WCmmUK91NMwCYQon+AEaECD/EjFBnkXzpmCfU2c0PTkewXlMY8HA/ey4cIEw=,iv:nga1eym/7oogWY+NJKQJDjbbqKBV3bFzHXo/FTMUibg=,tag:F3tdzq8OXdxxDXVuZidYDQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
