apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:Nfnpn00rkHMuSwSjaU9vmrZ7sG9tnYT/42PCzg==,iv:8y4LW86Zv+R+kTaDTDkq9a2oWTY9cEnWAJUth9pl0Uw=,tag:fDQ1PhMZvNxjLc1pvGtP0g==,type:str]
    settings.yaml: ENC[AES256_GCM,data:sxXkn6w0fJokhliWJ0lFnQUIMDBnnw7FdTll+TkuHfrp44bIF+pE4Fq/Y5qy8OjOlf5U7W1SvOjPO1/FdtY7SEC7a36rSsxLCGG0DJQRAjWTnc+QFnDE4LqkzCK6bBckW44sHg+7IRXbEJprD4/oixcYJ3/0Gz4aUhMHoHsrjjw56RkdaSfT2ZZvGt6OqSTdrPobhrqPEK94sjGGg0nyA8YwZv5J+AZI9bpHgbXa95C0j7FuggapWj7IAt6kkfTrNyzbsLmJsn7p3SZ8m/N6ckagXGhR1KFzoWj7RsqNDLPcCYFX5+WBBlNOqMLOGhyW3JsNmjWPJF1wSuTL56QagzPiq7GkQ5nvTmlePDhlPeLRGm0iBoMdIp174nQInWo7vaYnVdJw3Dvv6LtSrUwyiLmSnNarz06ToJ9fMV0JLs1nRr8S0LLTuGzI17aU69txcvGPUEjp11P9DoTUDtLLWwPL8tKh2S+fl0tLRwgWXbp+ZILy/W1imOEiFCA+s0MOO75/LHv60rKKWufh6FGmlo2UmB6roOGSMG6s1N7a0Fn8hMcqAJvflFhgXPDXcYYdHgzdg91hsWKSP2Z/Kqs6O4viZp2ZxbLYER43rhPQB7qpYI6DDptUt3w4LW0=,iv:ItD/wl6jv+CH7yycOsN7iZepJfcFVxiH6/TjgaxnDtU=,tag:0GRnuv5JqjUkzLb7zbN+TA==,type:str]
    services.yaml: ENC[AES256_GCM,data:YjHV6tcOGSEa1W+T+ZVpkwNO7p/Iy87/mh1qNO/t9qeRP3hBq44VTmUUPSvk13R7v/wFs0xh2dt7L1qmEgPTugxjJDpN7NsLk5HbRSCxX1SOOaVh70HmBWm4sr6blX5FEJo8cbO4sSbAxivOazISQXV3JSon+LIfYvJiHKe62KcBx5Fh/2G3NZniRS4L6l6B8Kq+FGFwm4Y4tEqHcA==,iv:MSTVzwZ1aREcvJQWIwr7oLr3Lv+XfuxGKRTz7aNe5lw=,tag:XWMEv6ZPxl7Ws1Myf+d7dw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d2dPbjVJK3pUUlZudkRv
            QlFLZXpNM1JiTHZxT1hDV3RXWkRHUXVUaTJvCmFXYUl4NUtqUlRnWFZKa0c5L1Vk
            Z3c4WjgwTnVwRUxkV2hYMGxjdm1Fb3MKLS0tIFBTbGl4UDNHbUhTODdhWVFOZW9w
            Z2t5M3h6Wm8ySno0RVRjdGFUNFgxdGcKJBcUfWw5Zh1W5sOQkpZOwM7Gcs6v6tnA
            ayVNW95iZ9rufWiyI2J5eBDhASWz52yotS6xqw5kwxYfwBP7u83D3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T23:11:20Z"
    mac: ENC[AES256_GCM,data:Kfnhwctn6ZZWsOX5In2RKHd4LXoBdx342g53K8wqIKwc5unLjhGy2Ek37lSg0VA2B1AaAL0UUzDa1oNlFiFAjYAMsoXoFs6Q8rUT4FQT6NPCSLV6SsC/wI2pO8DgVqqI1tD3EJLdF/JHEyKrlg6xkYuzfXHoJ1JxQnDN6CVz1wY=,iv:ljh2lPSfMNWo+l2siErQkmV8LKGNDtFjvQJBmaezUjI=,tag:9MiQckZ35JKD6j2q7n2B7Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
