apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:VGM70aLk3XhPl6o+rk3xiWDE1fVifzxTFNAR6w==,iv:mGIkIjEP6YRdgX5w0xlHDREfl1wGEIax8akvpTxK7dw=,tag:K4py21VmeXz5RWnGaF4QEA==,type:str]
    settings.yaml: ENC[AES256_GCM,data:v2r0cgxpnkGE/PRvvv8Rfa+9BYW86iUkuTiRvwqTToCsgbfcJaKtlRktNWPZ2vBs91YNh8A8lBxxQ+DhmRafvqu9mG6Fjv3LX8w8WJAixqWEWrF+UBecj8dwS+AkYqLROPmtUoTDof+xUELythig1bz60ST6jlPH+Zrpan+dVbPyeMMlyx1jEw6cpDpbY+Nw0dlyO+VGlpmjzOOB9daMjzRk3TTGxqOdiD6QsecZbEBb1QTu5W4J71psilJTqNBVBxnA7rjNGb0W/veITQF2UOZpjJmpSm86n5uTntkuCz7ne5hzUnBQlHJbY+nGVgUlx/1CWmAso6Rs4M2BNj+y+2WNXpjdj7k0jYMRLFQLSuWT1kPoGOe+P/yBe9M+erj99uK0fLGOQRxKjZwiXWVlERiyk5xddvt9ZoxpbgJydYY+M4CqVoz6fp1BYjV9e4cT3MoqSLEWz79JW0t+82z/v9FyD2dL9kWCuG3SUFm1uAuTIEeHrOYWA6V15HjNeWniY9kgIa+Ndy7dSBqAV9LjRf+eiOw6ml3q0T0mWgwsMuKaxPfzvTIPQBlP9fMOBLiOW1wld8atu/Qq1ELFHhZjIuwLwze9BfudSaxRFuS4sSdq2cF1yE/TgwkUtMc=,iv:fHQX8mkQh1Nxotw14ZJCaQkIZ/ulSWdP79sR7uLn624=,tag:eQJOhcNntV3P6b7zmOLVjg==,type:str]
    services.yaml: ENC[AES256_GCM,data:M0b5p6AIwPouGxh7oevBLFMfhUUo8lD4Q6XQPh540isKWH+AXLnvZslWjIzLAkIWuPEBV9BIizDz19F1wzao+V7tPJCRH0rVQa/SUo2iwNFA2+S7Ivqvb7/05Z5lOT+6xuV3eJCdaWDwInWM9D8sw46dhdb7Ss1TGljOrbFz7gAXSmgtjdcIWnmnfUmb8kab7EGgp3COEta5MFgqMQ==,iv:m2N5JiLfOMprM7VniFmCZ2rhgby7DHT9FUWIEQQxy7I=,tag:xoKPnKZ55VpvvYbBP2qQhg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2blBEN1pDOXM3Q3NsZWF5
            OTN1NHI3VHI1N2V5NlpqeEowdnAzMjlBRjFjCjhiYlJGU2dJd1pKT2NIWFUwQVJL
            ZE9GNHN5VStQRnNGcGIvS0NCVWN2SU0KLS0tIDZoVENrK1Q2Y0k3R25Jeldzcm13
            QzJNWVlyS2RieG9qU0NGRms4MG53OVEKioKyVaUun6Y5RwW/lI7r2as4PdF/zcgO
            sKmCuSfkHUWVt0cAG+CH5S6Vrymc/k5Kc9wCthgREKJLcjyFhEujWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:01:14Z"
    mac: ENC[AES256_GCM,data:9M/PVxOK0t85eYUAZs/UP/AJLMUzI9pbaXQOL6pTDsmeuYI1ArYpLSNo8yGQ1eySXRIEGcXsdoRcreciZLZrvyA4CyxOqIdy3Um8K6hutIQPyOxl6ZYW5hruYgEgW5Qp2Z1YVG2Hu6Gz3gr5jjn3I/AzqKSvbZ+E7BYdKm7b49I=,iv:g/LHRenM66ilhfTlscrFXwnWOyQ8aWud0yFHkX9DXOw=,tag:bCjouBvE9VBKVgniaDtqag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
