apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:MnWhAjm8tvEmtoqlGREGOrSus8cmoAqYbn6EsQ==,iv:emDAYiCnJ/pQHvuzMxobT4FBkX6YvzLR+Rw+GSCjvqE=,tag:mq5pb/fNCpANFiidjwokBQ==,type:str]
    settings.yaml: ENC[AES256_GCM,data:pxa3q1Vl3NyX4iuPQ6Yl7wJPZnZ1GJX1Rnr0ZrpJYum2Yfg3cC9wkuj/I2w4CKI98tMoYAPtDjSLkKV8xE3D7Df0wSn1N9y4QbEobIs/Lq/4kjcwKjsOU70e5tWmbsCDEllD6sqz67lICh5bGSYChQTn7afX0fRCOv9gC3fU5Fmn0z60EYGSwLkCws4qKHmtQgKiIatAm5Nwz+bgUynYLaw370SCuzzIBZ0a6FbSHNc7O6pWXxwP1q1GNJ3HoSEXAwKlC5ZG22/RJFrYpGB95TsIOP4e9oUeLQWEY94MbwjrV5Q1KQHPbS73T/+MvHM8hW5oQtg+CiJv1OFIaj1T7aoyFXOl3FcI2i/L4g1E8/Kj57ysM7wl0IktIr8sdTrOnl2viYzjmmnCkeR0I8ONwsQnLnGfiPUlSyZ4ShxJjhG1G/ghbrd26TteG0WqkEokhynGvhN2o5FZBY/Rt6aWC9RDTjvkaAmKIBtQNtICn07fktma8898ds0YRrBLmqyhj1hxMMZg2EdqXUqg2ko78FCXKmFQ0sOWmL0+YEpjbKUJGIuoPKSlCDcoqUlohJmNwskRoMnvNEGxatisyN9cM2gbGeTkU2ECA1J/mxRdXP8a+bl9Li4JzeZ2WcY=,iv:TR9zaNcCelPdzbZMLGTYwyWSRYQjeuNKxvtJF9fYGns=,tag:HCRHg3SQJesVEUVmX1xALQ==,type:str]
    services.yaml: ENC[AES256_GCM,data:HDjpfwSWOVBl9heyJda1VPLiOI4lqdgyKgf2Zj9UK12+6oGBodwKF3gczLw38ax1tMI0oWoho9ATEI63TH9m5GxTQjQU7+0UjVSQ77M/WYw27j1pCKhGavwsdLjIcDFMLhwIOROLitubMC/WbL8kIDLMiDPirpX+IF9UhTlFu3HhJgD3QcBkSKy1jwilPXhzFRqw+XKBBTl0gBQy9g==,iv:R4SqIgD7SJAqfNBZH8RFW90+k0H1pGgcRfFwv9Xkens=,tag:GpA/HWLgR1DbuHjwWN9xqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRHNWNm9BRUlYeHphd1dQ
            djhGSlpwVFNsRDF4cUU5RnhwYVZHaUZjd1hjCktIV2VETVZaR1hWeVYzZVo5SHhP
            cHhJTHF3eityUDQ3V2xhRGlBdUJIWG8KLS0tIDhSazEvN1plMnhwTmlYV0g0T0Ft
            OXpxTW1qWkVUSXZLQ3BZeDJST3pNODAKcriLFQh21RX5Ct4kiTf5gVjFkUdHIemn
            tdl2/zYsGsszAl778EBke2O8vBUbY1HiYIrKq20T33DzBKlWqNcN2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:40:42Z"
    mac: ENC[AES256_GCM,data:I2uAKpVjkss2SfZbJZqItwsPN41HhWXB9zAEE4YXn3QLlUTWSVS8pp1zu5MFrNPUx6XXdMoh3JKGQCQmBcIoA+9AZG5aaqapzDpXQNktO1Kf9vQpfFHpp+n8DLu3RRYN/un1isntXhQnGhWpgrDYRyZx7rjZx3L13KfrFH8NJRs=,iv:tZaVOVWVibo3DDhsgXbZonApLTcn7a+w8Nv8Qx9yb2Q=,tag:KCsK/X0EN7YhFp0pD0lMtw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
