apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:kcjU1fmo8yQ+sDn5kHgpsBbXYpJKph5/DqSiBA==,iv:0vtjeXyNeGT0D2/HGiMzIIIkdKabmu3U7/X+ycBtdx4=,tag:eC1r3IUW4hks37dFbWQkIA==,type:str]
    settings.yaml: ENC[AES256_GCM,data:s7uAlV10PAzwHdfYen/OWmdW4zjB/V9f2WbhRZxcKFPSBIDTriFsEkQdh4ZXfb8j1n7C5oZDt1eCerzddtMkgVEX5qau8jl1PF2guLg99TkJpVCFxvFmj4ZFHRg2sTE8t6hh8W91QyXFTuQ+D0Msz7nQBP62A1wy2FFzLVTs/SU9CBF5gS4wvZKbBgPdEWYevn/VzmuhtHyBhQh5miJUMY9ei4zyPTSs7r1C8/LNAzV9YOAWwfAFJz8BZkVPP2f8J6hnNtLfRrYxOxE3JgiTT5bQjGLRBgkjnciGFbSnjcnfgYV/6HvBbIyA3e+eLn9zdRp5UuWeYZ7EmTjSD70+CzNfecGp9ypj6uJ6nWsIFTcPRHGpaTb303/3sirtl7lTLiPbF50YuI9rK2q0z5W8KgAto1mwaBAAkcK2tMQ1MWe+55tEbf+1nxC7nxskEw6ot5rZZhCOiv+w2YDOP0R3LuAWpe4dGgecprYF15ur3EN99f6ZtmmMNwlWjCXcgSoBddoBwJQseUV7sN0dHBddEEbLBn6g+iuGZ6WXzU94+lZAYCRUlUcIF6oaNw/TaMW9tKB5yYptsvso4IQpYncRZsDxZxlfovSPhHu2Gthxn5kLrnSThj0ts/QufcM=,iv:BWonMoGmxlRuy6PvlROVQo17sAQLL0BYHrwUAUaJcBI=,tag:AAxOA7MUeFo6sdqkMQd2rA==,type:str]
    services.yaml: ENC[AES256_GCM,data:oYjJvuRHYpJR/QAk7Tr1K3z8HDtO6n31JTuHQAwxi365EbCzwox/HGdAkqzdFPA3GdNMqOrw9BsFSyBGY3d5V5+2HFAEup4KELyWfyEvN3Hj9sj3HGf5uzGY7RCJ2syrscBYfrheUh01qUJo6segWllBOlDzGz/ffskks9+KBjvIBJryKq1D+GttwmuMmbSdRVPV/TflcQwr8Eg8lQ==,iv:U0as2WKyv64REm1LH2zNoknXQ9nDCqkNv3xkursqIQg=,tag:0WNXRtawCJ/eUD2KW1uZag==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSFZJMVpLdWY0UGptN0Ju
            WVJwYmxzNjNJNU5BOGU2WjZmbEFKU0RoQURRCk43RGV2RVFzNUlLS2hzVS9CTjEy
            WTNYaXlBUFZkWC9KNk1qcEtGbk02YWcKLS0tIGdFNEhuejRyTlRjUS95N2RPbFFh
            bmhkZTVhZkxEMGhXVjF5Zi9DbnU0Yk0KGi15e1A/dbjmshNr23zKnDEmVe4To3I3
            BxV2tSQA+9YZE9gekUGhs5zqrAObKFv1lzSbQTCuh7zdmwoNTH18EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:13:30Z"
    mac: ENC[AES256_GCM,data:EVBQMgPbrrtaFIkRBuqLBe0G+hmpP/DPAp66CcCdO7FvaydcFHBAixQXmY5dU558gsBUww2vJUD1hkFyOpkDjnHBe55mDI0FkxBkS8qdZIoxbhvjBRrQVr5MWlaPDBZ90n9sER085qtxSC6HmjV8o7NzOw+saVP0h16oQ2K/TKU=,iv:IkRAb0BzewUs42IhFrTJka3usK8HBI3joqLkmmBjsqY=,tag:bRNvgn7Fk6BEnjuMckedaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
