apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage-values
    namespace: homepage
data:
    kubernetes.yaml: ENC[AES256_GCM,data:bm0RTD9ShJQNSBZxMqdKBoOgD5cCEm8JdW7qqg==,iv:e+/3jFQfs59iqv+Rz9d4bEJ+ycht1lxefqynRYfKjPM=,tag:0az9IkzA5jFs57uOPfnKlA==,type:str]
    settings.yaml: ENC[AES256_GCM,data:K1s4CZecmFBU/6i2uCf8kd5l/WDoLJoZ+AHx1vc4Kc4HMBFBFh4zzJ/3NbF7midIhxHAVxCf+so1sUFdKNDYAQDkAXRka/O7s5H5QMpKWq+BE5CcqNHSj9mtiL/6WTQDXxA1cUDdPVdMHG/cG0+Dk7zgfO5EmpN/02Emt6GnOtg2T6cacXYoIIjF/+WQw+tdaFqejPSB83vYJ9KhTtup6XgRJR8p/G+Df54Sv8BlXhdTU+1brwHkLSU14iW1dkevSHQAP9wH3K3LKE9Tim80Ij6iz/u9tcFbCnX+AsZG/jvH3m57rNmii/LWQBsYrfH7U+LK3l1R3mG436piXCtU+nQbisMhK7pzkcqJshyPyo7THC9YizdJr+BSshKD0WWjA5lz+TSnwK3PEqO2aAPoONtXf4QUCU0Ug1XikAp5IoJm+bp+O4Ac+nd9Zt5Y1EYpyxKMOYOVopaDs54SfKFJPdREAChZzoFIyPe7P4IyRYRXUbcKjF141/iOeJENt+AMwV3fLM/3kph4NrPQ/cKlvcVK+v1ihtgNyA3LSXFNa1Fk+/JDU6jyT5arw6M50s2dlidCD2UEA1tKPCixbmdMDTE59SXTdzYkJ1hssKYdH4r4Zr+MoAESyQAgMo4=,iv:9HZF63FBaBht7vqR1PjACbsIHJ3zY65pzLBCgE6/Jek=,tag:r1Gni+7FuMi+S+qerWebwA==,type:str]
    services.yaml: ENC[AES256_GCM,data:ZCcKd6AntMEadeJFDFSNEgd2hddE0NOzkoO0q0diuWtyxsvLjSFZWKyiba0xsHB98GqQpBMSOJC7QLrtVvRaEmJv1Q2/+Cr3NNIXKVXr5r90JIFDnKbarhUIrbb3SVQ6KcFo/jFqop49h34iiRU0wX2rnuXbrq/q6RgYmC73P6/skQ0zTV9oICr6nOJ9dx8NtYNEjZQ/kGM8E5ZbFg==,iv:7HJFC7adq+YIjwUH6GxJ9d8S6VyCD7dq1+LuTnkqcmI=,tag:iyhHHQzCHPX3Pm7Wqgj3nQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdis0VDZoVEdCcCtxbmw0
            THhLTm5IWi91bEhDR2VUbTZrM3o0N1JsckJ3CnlPdjFTemJDdTJhVy85eDNNVSty
            RmhMS28rWi9iQ3NRTzFqNFYxRTduSFEKLS0tIEhLbGtCWWlkdUxRR1dlUzc3akZw
            blNkKzhxQnhGVkhndjIvekgxenpnbnMKoS2dEpXcfA3c02piP1BX12OM2ib8/9j6
            RjBNPXljGM+kjGxK4upIzCN5qPwhkz3YBYk6W8hlt4UBlyoFBF0IFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:16:06Z"
    mac: ENC[AES256_GCM,data:SvvRkwu/WFurW+xJUD6C5UnMsqjUT+w9IGMRmImy8q4LF7RrbtOLzFbxULXsXL2mZs15JJqGWtEKoee3sE6vVCMlWtuKIXznc6SbUkpKKV3K0jSQ9GtezIXi/ggzCnSMFgHrYFuFNudJaRsJaqfZLlsCG9V1WoxAHYISlrAj9Es=,iv:rHWhY8a7/Ip3exvdAKBzYXiOjZSxoxS1aSOquHUwFyc=,tag:/wBYmdvAtbpDbH53qN+H2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
